from django.core.management.base import BaseCommand
from academy.models import Module, Lesson, Quiz, Question, Choice, DiagnosticAssessment

LEVEL1 = {
    "What Is Health Research?": [
        ("Start with the idea", "text", "Health research is a structured way of asking a question about health and collecting evidence that can help answer it. It is different from simply looking something up, following routine practice, or describing what happened once. Research begins with a clear problem and uses a planned method so another person can understand what was done and judge the evidence.\n\nIn health, research can describe a problem, identify risk factors, test an intervention, understand people's experiences, or improve how a health service works. A good research question is specific enough to answer with evidence. The question should guide the design, data collection, analysis and interpretation.\n\nExample: “How common is self-medication with antibiotics among medical students at a university?” is a researchable question. “Antibiotic use is bad” is a statement, not a research question.\n\nResearch does not begin with a result you want. It begins with a question you are willing to investigate honestly."),
        ("Research or routine practice?", "activity", "A clinic notices that many patients miss follow-up appointments. Staff begin calling patients one week before their next appointment as part of routine service improvement. If the team only implements and monitors the change for local improvement, that is primarily service practice. If the team develops a systematic study to answer a defined question, selects participants and variables in advance, analyzes the data, and intends to generate generalisable knowledge, it becomes research.\n\nAsk yourself:\n1. What question is being answered?\n2. Is there a planned method?\n3. What evidence will be collected?\n4. Who needs to review or authorize the activity?\n5. Is the goal local improvement, generalisable knowledge, or both?\n\nThere can be overlap between quality improvement and research, so students should follow the requirements of their institution and responsible governance or ethics authority."),
        ("Why research matters in Rwanda", "text", "Research helps health workers move from assumptions to evidence. In Rwanda, research questions may come from malaria control, maternal health, non-communicable diseases, antimicrobial resistance, digital health, laboratory practice, health financing, or the experience of students and patients.\n\nA strong study can show the size of a problem, reveal who is affected, explain why a service is difficult to access, or test whether an intervention is useful. Research does not automatically change policy or practice; findings must be interpreted, communicated and considered alongside feasibility, ethics and existing evidence.\n\nA practical mindset is: define the problem, ask an answerable question, choose a suitable method, collect trustworthy evidence, analyze it carefully, acknowledge uncertainty and communicate what the evidence supports."),
        ("Worked example", "activity", "Scenario: A university health centre wants to know whether a short malaria-prevention education session improves student knowledge.\n\nStep 1 - Question: Does the session improve malaria-prevention knowledge among students?\nStep 2 - Outcome: a defined knowledge score before and after the session.\nStep 3 - Method: choose a design that can compare knowledge over time or between groups.\nStep 4 - Evidence: use a clear questionnaire and document how it was administered.\nStep 5 - Interpretation: describe the observed change without claiming more than the design can support.\n\nNow create your own health example and write the question, main outcome, data source and next step."),
        ("Check your understanding", "text", "Before the basic assessment, you should be able to explain what health research is, how it differs from routine practice or casual information gathering, why the research question comes before the method, why evidence is documented systematically, and why ethics and governance belong in responsible research. If any point is unclear, review the lesson before taking the quiz."),
    ],
    "The Health Research Lifecycle": [
        ("See the whole journey", "text", "The health-research lifecycle is a connected sequence: identify a problem, review existing evidence, define the question, choose a design, plan ethics and governance, collect data, manage and analyze data, interpret findings, communicate or publish, and preserve the research record.\n\nThe stages influence one another. A poorly defined question creates problems for the design. A weak data plan creates problems for analysis. Poor reporting makes useful findings difficult to trust or reproduce."),
        ("From question to plan", "activity", "Take a simple question such as “What factors are associated with missed antenatal-care visits in a district?” Map the next five decisions. Start with evidence already available, then identify the study population, possible variables, ethical considerations and the kind of result you need. The aim is to understand how decisions connect, not to memorize one rigid sequence."),
        ("Governance is part of the lifecycle", "text", "Research involving people, identifiable data, biological materials or interventions may require ethics review, institutional permission, regulatory authorization or other governance processes. These should be planned before activities that require approval begin. A responsible researcher also plans data security, authorship, documentation and conflicts of interest early."),
        ("Worked example", "activity", "A student notices low vaccination knowledge among peers. First, check whether the question has already been answered. Next, define exactly what “knowledge” means. Then choose a suitable design, think about recruitment and consent, plan the questionnaire, decide how data will be stored, and only then conduct the study. After analysis, communicate strengths and limitations. Write the lifecycle for your own example in ten short steps."),
        ("Ready for assessment", "text", "You should now recognize research as a process with linked decisions. Different studies may revisit earlier stages. The important skill is understanding why each stage exists and how evidence, ethics, methods and communication connect."),
    ],
    "Research Questions and Objectives": [
        ("What makes a question researchable?", "text", "A research question identifies what you want to find out. A strong question is clear, focused, feasible and answerable with evidence. It identifies a population, issue, exposure, experience, intervention or outcome where appropriate.\n\nCompare: “Why is diabetes a problem?” is too broad. “What proportion of adult patients attending X clinic have controlled blood pressure?” is more specific. The best wording depends on the design and purpose of the study."),
        ("Questions, objectives and hypotheses", "text", "The question states what you want to know. The objective states what the study will do. A hypothesis is a testable expectation used when appropriate. Example: Question - “Is sleep duration associated with academic performance among medical students?” Objective - “To assess the association between sleep duration and academic performance among medical students at X university.” Objectives should be specific enough to guide the methods and analysis."),
        ("Build one step at a time", "activity", "Start with a health problem. Write one sentence describing the problem, one research question, one primary objective and two secondary objectives. Remove words that do not help define what will actually be measured or explored. Then ask: Could another researcher tell what evidence I need from this wording?"),
        ("Worked example", "activity", "Problem: students report difficulty accessing research articles. Question: “What barriers do health-science students report when accessing scholarly articles?” Objective: “To describe perceived barriers to accessing scholarly articles among health-science students at X institution.” Secondary objectives could explore differences by year of study or access to institutional subscriptions."),
        ("Check your understanding", "text", "Remember the sequence: problem -> question -> objective -> method. Do not choose a statistical test or questionnaire first. Start by deciding exactly what you need to learn."),
    ],
    "Evidence and the Research Landscape": [
        ("What counts as evidence?", "text", "Health evidence comes from different sources, including primary research studies, systematic reviews, clinical guidelines, surveillance reports and policy documents. Each source answers different questions and has different strengths and limitations. A primary study may provide original data; a systematic review summarizes multiple studies using an explicit method; a guideline translates evidence into recommendations and may also consider values, resources and feasibility."),
        ("Search before you repeat", "activity", "Before starting a new study, ask what is already known. Search using the main concepts of your question. Record the sources searched, key terms and important findings. The purpose is not to prove your idea; it is to understand the evidence landscape and identify what remains uncertain."),
        ("Evidence is not a popularity contest", "text", "Do not judge a source only by how impressive its journal or website looks. Ask: Was the study appropriate for the question? Was the method clear? Could bias have affected the result? Are the participants relevant? Are the conclusions supported by the data? A heavily cited study can still have limitations."),
        ("Worked example", "activity", "Suppose you find a news article, a cross-sectional study and a systematic review about malaria prevention. For a scientific background, the primary study may provide useful local data, while the systematic review may help summarize wider evidence. The news article can help you understand public communication but should not automatically be treated as the strongest scientific source."),
        ("Check your understanding", "text", "Your goal is not to memorize a rigid hierarchy. Your goal is to match a source to the question and judge its quality, relevance, limitations and currency."),
    ],
    "Scientific Communication": [
        ("Why research must be communicated", "text", "Research becomes useful when other people can understand and evaluate it. Scientific communication includes protocols, posters, oral presentations, reports, manuscripts, journal articles, policy briefs and public explanations. Each format has a different audience and purpose. A manuscript is a structured scientific report. A journal is a publication venue. Peer review is a quality-assessment process; it does not guarantee that every finding is correct."),
        ("Match message to audience", "activity", "Take one finding and explain it three ways: in one sentence to another medical student, in a short paragraph to a hospital manager, and in plain language to a member of the public. Keep the meaning and uncertainty consistent. This is a research skill, not just a writing exercise."),
        ("The basic scientific story", "text", "Many health research reports follow a logical flow: why the problem matters, what was asked, how it was studied, what was found, what the findings mean, and what remains uncertain. A good paper does not hide limitations or inflate significance. Clear communication follows the evidence rather than trying to make the study sound more impressive."),
        ("Worked example", "activity", "Finding: “In this sample, 52% of students reported consistent insecticide-treated-net use.” A scientific statement can describe the proportion and population. It should not automatically say the intervention caused the behavior unless the design supports that conclusion. Practice rewriting one result without adding a causal claim."),
        ("Check your understanding", "text", "Before assessment, make sure you can distinguish a research report, journal, reviewer, author and reader, and explain why communicating limitations is part of scientific quality."),
    ],
    "Research Integrity Basics": [
        ("What research integrity means", "text", "Research integrity means doing research honestly, transparently and responsibly. It includes accurate recording, appropriate authorship, respect for participants, careful data handling, honest reporting and disclosure of important conflicts. Fabrication means making up data. Falsification means manipulating research materials or results dishonestly. Plagiarism means presenting another person's work or ideas without appropriate attribution."),
        ("Integrity starts before publication", "text", "Good integrity begins when the question is planned. Keep decisions documented. Do not remove inconvenient observations simply because they do not support a preferred story. Do not change the primary outcome after seeing results without transparently explaining the change. Protect participant confidentiality and follow approved procedures."),
        ("Worked scenario", "activity", "A student notices that several questionnaire responses are incomplete. The supervisor suggests deleting all incomplete responses without recording how many were removed. What should the student do? The responsible approach is to document the issue, follow the analysis plan where possible, discuss appropriate handling with the research team, and report important exclusions transparently."),
        ("Authorship and contribution", "text", "Authorship should reflect meaningful scholarly contribution according to the relevant journal or institutional standards. People who helped with administration or general supervision may deserve acknowledgment rather than automatic authorship. Teams should discuss roles early and document contributions."),
        ("Check your understanding", "text", "Integrity is not simply “do not cheat.” It is a system of honest decisions that allows others to trust the research record."),
    ],
}

DIAGNOSTIC = [
    {"prompt":"Which statement best describes health research?","answer":"B","options":["A. A personal opinion about health","B. A planned process for answering a health question with evidence","C. Any online health search","D. A treatment given in routine care"]},
    {"prompt":"What should usually come before choosing a research method?","answer":"A","options":["A. A clear research question","B. A preferred result","C. A journal title","D. A statistical formula"]},
    {"prompt":"Why do researchers review existing evidence?","answer":"C","options":["A. To copy another study","B. To guarantee publication","C. To understand what is already known and what remains uncertain","D. To avoid writing a protocol"]},
    {"prompt":"Which is an example of a research objective?","answer":"D","options":["A. Health is important","B. I like malaria research","C. Malaria should decrease","D. To describe malaria-prevention practices among students"]},
    {"prompt":"Why is documentation important in research?","answer":"B","options":["A. It makes the study longer","B. It helps others understand what was done and why","C. It guarantees positive results","D. It replaces ethics review"]},
    {"prompt":"When should ethics be considered?","answer":"A","options":["A. During planning, before activities that require approval","B. Only after data collection","C. Only after publication","D. Only when results are negative"]},
    {"prompt":"What should you do when an important claim is uncertain?","answer":"C","options":["A. Publish it immediately","B. Remove the citation","C. Verify it using appropriate evidence","D. Ask an AI tool and accept the answer"]},
    {"prompt":"Who should use the Academy entry assessment?","answer":"D","options":["A. Only professional researchers","B. Only administrators","C. Only people who have never seen research","D. Anyone who wants a suggested starting point"]},
]

class Command(BaseCommand):
    help = "Upgrade the RSRE Research Academy V41 learning content and beginner assessments."

    def handle(self, *args, **kwargs):
        for module in Module.objects.filter(active=True).order_by("level__number", "pathway_id", "order"):
            if module.title in LEVEL1:
                specs = LEVEL1[module.title]
            else:
                objectives = module.objectives or [module.summary or f"Understand {module.title}."]
                specs = [
                    ("Core concept", "text", f"{module.title} is taught from first principles. Start with what the term means, why it matters in health research, and where a student researcher would encounter it.\n\nKey learning point: {objectives[0]}\n\nBefore moving on, explain the idea in your own words and identify one situation where you would use it."),
                    ("Key ideas", "text", "Break the topic into its main parts. Define unfamiliar terms, identify the decision each part supports, and note one common beginner mistake. Keep the question, method, evidence and interpretation aligned."),
                    ("Worked example", "activity", f"Apply {module.title.lower()} to a realistic Rwanda/Africa health-research scenario. State the problem, explain what you would do, identify the evidence you would consult, and describe what you would document."),
                    ("Practice task", "activity", f"Write a short response showing how you would use {module.title.lower()} in a student research project. Focus on reasoning and application rather than advanced terminology."),
                    ("Check your understanding", "text", "You are ready for the basic assessment when you can explain the core idea without notes, identify a sensible example, and recognize a common mistake."),
                ]
            module.summary = module.summary or f"Build a practical understanding of {module.title.lower()} for health research."
            module.save(update_fields=["summary"])
            for order, (title, kind, body) in enumerate(specs, 1):
                Lesson.objects.update_or_create(module=module, order=order, defaults={
                    "title": title, "lesson_type": kind, "body": body, "video_url": "",
                    "resource_urls": [], "estimated_minutes": 30 if kind == "text" else 40,
                    "required": True, "active": True,
                })

            quiz, _ = Quiz.objects.update_or_create(module=module, defaults={
                "title": f"{module.title} - Basic Knowledge Check", "pass_mark": 80, "attempts_allowed": 0,
            })
            quiz.questions.all().delete()
            pool = [
                (f"What is the main purpose of learning {module.title.lower()}?", ["To understand and apply the core idea in health research", "To memorize advanced formulas immediately", "To choose results before data collection", "To avoid documenting decisions"], 0, "The first Academy check confirms basic understanding and responsible application."),
                ("What should a beginner do first when approaching a research task?", ["Define the problem or question clearly", "Choose a desired conclusion", "Skip existing evidence", "Copy another study without checking fit"], 0, "A clear problem or question gives the rest of the process direction."),
                ("Which action shows good research practice?", ["Make important decisions transparent and document them", "Change methods whenever the result is inconvenient", "Hide limitations", "Remove uncertain findings"], 0, "Transparent decisions support trustworthy research."),
                (f"Which statement best fits {module.title.lower()}?", ["The approach should match the research question and context", "One method is always correct", "More complicated is always better", "Results should be selected before analysis"], 0, "Research methods and decisions depend on the question and context."),
                ("What should you do when an important research claim is uncertain?", ["Verify it with appropriate evidence", "Publish it without checking", "Remove the uncertainty", "Treat an AI response as automatically correct"], 0, "Verification is a core research habit."),
                ("Why do researchers describe limitations?", ["So readers can judge how far the findings can be trusted", "To make the paper look weak", "Because every study must have negative findings", "To replace the results section"], 0, "Limitations explain uncertainty and boundaries."),
                ("Which is a good research habit?", ["Keep a record of important decisions and changes", "Change plans secretly", "Delete inconvenient observations", "Avoid keeping notes"], 0, "A clear record supports transparency and reproducibility."),
                ("How should evidence be judged?", ["For quality, relevance and limitations", "By popularity alone", "By one source only", "By whether it supports your preferred idea"], 0, "Evidence should be evaluated rather than simply collected."),
                ("When should ethics and governance be considered?", ["During planning, before activities that require approval", "Only after publication", "Only if results are interesting", "After recruitment is complete"], 0, "Ethics and governance are planning responsibilities."),
                ("What is the purpose of a worked example?", ["To show how the concept is applied in a realistic situation", "To replace the lesson", "To guarantee the same answer in every study", "To test advanced expertise"], 0, "Worked examples connect explanation to practical use."),
                ("What is the purpose of the basic knowledge check?", ["To confirm foundational understanding before progression", "To test whether the student already has professional expertise", "To guarantee publication", "To replace practical work"], 0, "Early assessments should confirm foundations."),
                ("If you are still unsure after the practice task, what is the best next step?", ["Review the relevant lesson and try again", "Guess and submit", "Skip the topic forever", "Choose the longest answer"], 0, "The Academy is designed around learning, practice and reassessment."),
            ]
            for i,(prompt,choices,correct,explanation) in enumerate(pool,1):
                q=Question.objects.create(quiz=quiz,order=i,prompt=prompt,question_type="single",explanation=explanation)
                for j,text in enumerate(choices,1): Choice.objects.create(question=q,order=j,text=text,is_correct=(j-1)==correct)

        DiagnosticAssessment.objects.update_or_create(id=1, defaults={
            "title": "Research Academy Entry Assessment",
            "description": "An optional beginner-friendly diagnostic used to recommend a starting point. It is not an advanced exam and does not replace module assessments.",
            "pass_mark": 70, "active": True, "questions": DIAGNOSTIC,
        })
        self.stdout.write(self.style.SUCCESS("RSRE Academy V41 content upgrade complete."))
