import { useEffect, useState } from "react";
import Link from "next/link";
import DashboardLayout from "../../../components/DashboardLayout";
import api, { absoluteUrl } from "../../../utils/api";

const TYPES = ["organization","university","hospital","research_institution"];
const LABELS: Record<string,string> = {organization:"Organization",university:"University",hospital:"Hospital",research_institution:"Research Institution"};
type Partner={id:number;name:string;description?:string;website?:string;type:string;country?:string;logo?:string|null;status?:string};
const empty={name:"",description:"",website:"",type:"organization",country:""};

export default function PartnerManagement(){
 const [items,setItems]=useState<Partner[]>([]); const [form,setForm]=useState(empty); const [logo,setLogo]=useState<File|null>(null); const [editing,setEditing]=useState<number|null>(null); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
 const load=async()=>{try{const r=await api.get('/partners/');setItems(r.data?.results||r.data||[])}catch(e:any){setMessage(e?.response?.data?.detail||'Could not load partners.')}};
 useEffect(()=>{load()},[]);
 function reset(){setForm(empty);setLogo(null);setEditing(null);setMessage("");}
 async function save(e:any){e.preventDefault();setLoading(true);setMessage('');try{const fd=new FormData();Object.entries({...form,status:'active'}).forEach(([k,v])=>fd.append(k,String(v)));if(logo)fd.append('logo',logo);if(editing) await api.patch(`/partners/${editing}/`,fd); else await api.post('/partners/',fd);reset();setMessage(editing?'Partner updated successfully.':'Partner added successfully.');await load()}catch(e:any){setMessage(e?.response?.data?.detail||'Could not save partner.')}finally{setLoading(false)}}
 function edit(p:Partner){setEditing(p.id);setForm({name:p.name,description:p.description||'',website:p.website||'',type:p.type||'organization',country:p.country||''});setLogo(null);window.scrollTo({top:0,behavior:'smooth'});}
 async function removeLogo(id:number){try{await api.post(`/partners/${id}/remove-logo/`);await load();setMessage('Logo removed.')}catch(e:any){setMessage(e?.response?.data?.detail||'Could not remove logo.')}}
 async function remove(id:number){if(!confirm('Delete this partner permanently?'))return;try{await api.delete(`/partners/${id}/`);await load();setMessage('Partner deleted.')}catch(e:any){setMessage(e?.response?.data?.detail||'Could not delete partner.')}}
 return <DashboardLayout role="administrator" roleRequired="administrator" title="Partners & Supporters"><div className="space-y-8"><div><Link href="/dashboard/administrator" className="text-sm font-bold text-emerald-700">← Back to Administrator Dashboard</Link><h1 className="mt-3 text-3xl font-black">Partners & Supporters</h1><p className="mt-2 text-slate-600">Create, edit, replace logos, remove logos or delete partner records. Changes appear on the public About page.</p></div>
 <form onSubmit={save} className="bg-white rounded-3xl shadow-sm border border-emerald-100 p-7 grid gap-4 md:grid-cols-2"><h2 className="md:col-span-2 text-xl font-black">{editing?'Edit partner':'Add partner'}</h2><input required className="field" placeholder="Organisation name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select className="field" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{TYPES.map(t=><option key={t} value={t}>{LABELS[t]}</option>)}</select><input className="field" placeholder="Country" value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/><input className="field" placeholder="Official website" value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/><textarea className="field min-h-28 md:col-span-2" placeholder="What does the partner support?" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><label className="md:col-span-2 block"><span className="font-semibold text-sm">Partner logo</span><input className="mt-2 block w-full" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={e=>setLogo(e.target.files?.[0]||null)}/><span className="mt-1 block text-xs text-slate-500">PNG, JPG, WEBP or SVG · maximum 5 MB.</span></label><div className="md:col-span-2 flex flex-wrap items-center gap-3"><button disabled={loading} className="rsjh-button-green">{loading?'Saving...':editing?'Save changes':'Add partner'}</button>{editing&&<button type="button" onClick={reset} className="rounded-xl border px-5 py-3 font-bold">Cancel</button>}{message&&<span className="text-sm text-slate-600">{message}</span>}</div></form>
 <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{items.map(p=><article key={p.id} className="bg-white rounded-3xl border border-slate-200 p-6"><div className="h-24 flex items-center justify-center rounded-2xl bg-slate-50">{p.logo?<img src={absoluteUrl(p.logo)} alt={p.name} className="max-h-20 max-w-full object-contain" onError={(e)=>{e.currentTarget.style.display='none'}}/>:<span className="text-2xl font-black text-slate-300">{p.name.slice(0,2).toUpperCase()}</span>}</div><h2 className="mt-5 text-xl font-black">{p.name}</h2><p className="mt-1 text-xs font-bold uppercase tracking-wide text-emerald-700">{LABELS[p.type]||p.type} {p.country?`· ${p.country}`:''}</p>{p.description&&<p className="mt-3 text-sm leading-6 text-slate-600">{p.description}</p>}<div className="mt-5 flex flex-wrap gap-3"><button onClick={()=>edit(p)} className="text-sm font-bold text-blue-700">Edit</button>{p.logo&&<button onClick={()=>removeLogo(p.id)} className="text-sm font-bold text-amber-700">Remove logo</button>}{p.website&&<a href={p.website} target="_blank" rel="noreferrer" className="text-sm font-bold text-emerald-700">Website →</a>}<button onClick={()=>remove(p.id)} className="text-sm font-bold text-red-600">Delete</button></div></article>)}</div></div></DashboardLayout>
}
