import {useEffect,useState} from 'react'
import Link from 'next/link'
import ApplicationShell from '../../components/ApplicationShell'
import api from '../../utils/api'

export default function Certificates(){
 const [data,setData]=useState<any>({modules:[],levels:[],pathways:[]})
 const [badges,setBadges]=useState<any[]>([])
 const [message,setMessage]=useState('')
 useEffect(()=>{Promise.all([api.get('/academy/certificates/'),api.get('/academy/enhancements/')]).then(([c,e])=>{setData(c.data);setBadges(e.data?.my_badges||[])}).catch(()=>{})},[])
 async function download(path:string,name:string){try{const r=await api.get(path,{responseType:'blob'});const u=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u)}catch(e:any){setMessage(e?.response?.data?.detail||'Could not download credential.')}}
 function badgeSvg(b:any){const title=(b.badge__name||'RSRE Achievement').replace(/&/g,'&amp;').replace(/</g,'&lt;');const icon=b.badge__icon||'🏅';const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="700"><rect width="1000" height="700" rx="48" fill="#0f172a"/><circle cx="500" cy="250" r="155" fill="#10b981"/><text x="500" y="290" text-anchor="middle" font-size="120">${icon}</text><text x="500" y="475" text-anchor="middle" fill="white" font-family="Arial" font-size="38" font-weight="700">RSRE RESEARCH ACADEMY</text><text x="500" y="535" text-anchor="middle" fill="#a7f3d0" font-family="Arial" font-size="30" font-weight="700">${title}</text></svg>`;const u=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));const a=document.createElement('a');a.href=u;a.download=`${b.badge__code||'academy-badge'}.svg`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u)}
 return <ApplicationShell name="Research Academy" description="Your credentials and achievement record." nav={[["/research-academy","Academy Home"],["/research-academy/dashboard","My Learning"],["/research-academy/certificates","Certificates"]]}><main className="mx-auto max-w-5xl px-6 pb-16"><h2 className="text-3xl font-black">Certificates & badges</h2><p className="mt-2 max-w-3xl text-slate-600">Every completed module can become evidence you can keep, verify and download.</p><section className="mt-7"><h3 className="text-xl font-black">Module certificates</h3><div className="mt-4 grid gap-4">{(data.modules||[]).map((c:any)=><div key={c.certificate_id} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="font-black">{c.module_name}</div><div className="mt-1 text-sm text-slate-500">{c.certificate_id}</div><div className="mt-4 flex flex-wrap gap-2"><Link href={c.verification_url||`/research-academy/certificate/${c.certificate_id}`} className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-black text-white">Verify →</Link><button onClick={()=>download(`/academy/certificates/${c.certificate_id}/download/`,`${c.certificate_id}.pdf`)} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-black">Download PDF</button></div></div>)}{!(data.modules?.length)&&<div className="rounded-3xl border border-dashed p-8 text-slate-500">Complete a module to receive your first module certificate.</div>}</div></section><section className="mt-8"><h3 className="text-xl font-black">Badges</h3><div className="mt-4 grid gap-4 md:grid-cols-2">{badges.map((b:any)=><div key={`${b.badge__code}-${b.awarded_at}`} className="rounded-3xl border border-emerald-200 bg-emerald-50 p-6"><div className="text-4xl">{b.badge__icon||'🏅'}</div><div className="mt-3 font-black">{b.badge__name}</div><div className="mt-1 text-sm text-slate-600">Awarded {String(b.awarded_at).slice(0,10)}</div><button onClick={()=>badgeSvg(b)} className="mt-4 rounded-xl bg-emerald-600 px-4 py-2 text-sm font-black text-white">Download badge</button></div>)}{!badges.length&&<div className="rounded-3xl border border-dashed p-8 text-slate-500">Badges appear automatically when their achievement rule is met.</div>}</div></section>{message&&<div className="mt-6 rounded-2xl bg-rose-50 p-4 font-bold text-rose-900">{message}</div>}</main></ApplicationShell>}
