import {useEffect,useMemo,useState} from 'react'
import Link from 'next/link'
import ApplicationShell from '../../components/ApplicationShell'
import api from '../../utils/api'

export default function AcademyDashboard(){
 const [data,setData]=useState<any>(null); const [certs,setCerts]=useState<any>({modules:[],levels:[],pathways:[]}); const [labs,setLabs]=useState<any[]>([])
 useEffect(()=>{Promise.all([api.get('/academy/'),api.get('/academy/certificates/'),api.get('/academy/enhancements/')]).then(([a,c,e])=>{setData(a.data);setCerts(c.data);setLabs(e.data?.practice_labs||[])}).catch(()=>{})},[])
 const modules=useMemo(()=>data?.levels?.flatMap((l:any)=>l.modules||[])||[],[data]); const completed=modules.filter((m:any)=>m.completed).length; const progress=modules.length?Math.round(completed/modules.length*100):0; const current=modules.find((m:any)=>m.unlocked&&!m.completed)
 const unlockedLabs=labs.filter((l:any)=>current&&l.module_id===current.id)
 return <ApplicationShell name="Academy Dashboard" description="Your personal learning workspace." nav={[["/research-academy","Academy Home"],["/research-academy/dashboard","My Learning"],["/research-academy/diagnostic","Entry Assessment"],["/research-academy/certificates","Certificates"],["/research-academy/questions","Questions"]]}>
 <main className="mx-auto max-w-7xl px-6 pb-16">
  <section className="rounded-[2rem] bg-gradient-to-br from-slate-950 via-slate-900 to-emerald-950 p-8 text-white md:p-10"><div className="text-xs font-black uppercase tracking-[0.2em] text-emerald-300">Research Academy · My journey</div><h1 className="mt-2 text-4xl font-black md:text-5xl">Keep your research momentum.</h1><p className="mt-3 max-w-3xl text-slate-300">Every lesson, lab, assessment and certificate moves you forward. Academy learning is optional—you can enter where your existing skills fit.</p><div className="mt-7 flex flex-wrap gap-3"><Link href={current?`/research-academy/module/${current.id}`:'/research-academy/diagnostic'} className="rounded-xl bg-emerald-500 px-5 py-3 font-black text-slate-950">{current?'Continue learning':'Choose my starting point'} →</Link><Link href="/research-academy/certificates" className="rounded-xl border border-white/15 bg-white/10 px-5 py-3 font-black">View certificates</Link></div></section>
  <section className="rsre-stagger mt-7 grid gap-4 md:grid-cols-4">{[['Progress',`${progress}%`],['Modules',`${completed}/${modules.length}`],['Certificates',(certs.modules?.length||0)+(certs.levels?.length||0)+(certs.pathways?.length||0)],['Practice labs',labs.length]].map(([k,v])=><div key={String(k)} className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="text-3xl font-black">{v}</div><div className="mt-1 text-sm font-bold text-slate-500">{k}</div></div>)}</section>
  <div className="mt-7 grid gap-6 lg:grid-cols-[1.1fr_.9fr]">
   <section className="rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200"><div className="text-xs font-black uppercase tracking-[0.16em] text-emerald-700">Next best action</div><h2 className="mt-2 text-2xl font-black">{current?.title||'Start your entry assessment'}</h2><p className="mt-2 text-sm text-slate-600">{current?'Finish the lessons and practical work, then complete the assessed quiz.':'Your result helps you enter at the right level without forcing you through content you already know.'}</p><div className="mt-5 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{width:`${progress}%`}} /></div>{current&&unlockedLabs.length>0&&<div className="mt-6"><div className="font-black">Practical lab</div><div className="mt-3 grid gap-3">{unlockedLabs.slice(0,2).map((lab:any)=><Link key={lab.id} href={`/research-academy/labs/${lab.id}`} className="rounded-2xl border border-violet-200 bg-violet-50 p-4 hover:bg-violet-100"><div className="text-xs font-black uppercase tracking-[0.12em] text-violet-700">Practice</div><div className="mt-1 font-black text-slate-900">{lab.title}</div><div className="mt-1 text-sm text-slate-600">{lab.description}</div></Link>)}</div></div>}</section>
   <section className="rounded-3xl bg-slate-50 p-7 ring-1 ring-slate-200"><div className="text-xs font-black uppercase tracking-[0.16em] text-slate-500">Your momentum rules</div><div className="mt-4 space-y-3"><div className="rounded-2xl bg-white p-4"><div className="font-black">🎓 Earn as you progress</div><div className="mt-1 text-sm text-slate-600">Module completion can issue a certificate; level and pathway milestones remain separate.</div></div><div className="rounded-2xl bg-white p-4"><div className="font-black">🧪 Practice before publishing</div><div className="mt-1 text-sm text-slate-600">Labs build competence without affecting the protected RSJH editorial workflow.</div></div><div className="rounded-2xl bg-white p-4"><div className="font-black">🔔 Know what happens next</div><div className="mt-1 text-sm text-slate-600">Meaningful progress, feedback and credentials can surface through RSRE notifications.</div></div></div></section>
  </div>
 </main></ApplicationShell>
}
