from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[("academy","0008_practical_lab_assessment")]
    operations=[
        migrations.CreateModel(name="CourseEnrollment",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("status",models.CharField(choices=[("active","Active"),("completed","Completed"),("dropped","Dropped"),("waitlisted","Waitlisted")],default="active",max_length=20)),("enrolled_at",models.DateTimeField(auto_now_add=True)),("completed_at",models.DateTimeField(blank=True,null=True)),("last_activity_at",models.DateTimeField(blank=True,null=True)),("progress_percent",models.DecimalField(decimal_places=2,default=0,max_digits=5)),("course",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="enrollments",to="academy.academycourse")),("user",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="academy_course_enrollments",to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="AssessmentFeedback",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("submission_type",models.CharField(max_length=30)),("object_id",models.PositiveIntegerField()),("summary",models.TextField(blank=True)),("strengths",models.JSONField(blank=True,default=list)),("improvements",models.JSONField(blank=True,default=list)),("next_steps",models.JSONField(blank=True,default=list)),("created_at",models.DateTimeField(auto_now_add=True)),("reviewer",models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="academy_feedback_given",to=settings.AUTH_USER_MODEL)),("user",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="academy_assessment_feedback",to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="LearningRecord",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("event_type",models.CharField(choices=[("enrolled","Enrolled"),("lesson_completed","Lesson completed"),("quiz_passed","Quiz passed"),("assignment_passed","Assignment passed"),("lab_passed","Lab passed"),("badge_awarded","Badge awarded"),("certificate_issued","Certificate issued"),("course_completed","Course completed")],max_length=40)),("title",models.CharField(max_length=255)),("application",models.CharField(default="research_academy",max_length=50)),("evidence_type",models.CharField(blank=True,max_length=40)),("evidence_id",models.PositiveIntegerField(blank=True,null=True)),("metadata",models.JSONField(blank=True,default=dict)),("occurred_at",models.DateTimeField(auto_now_add=True)),("verified",models.BooleanField(default=True)),("user",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="academy_learning_records",to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="CourseCompletionRequirement",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("requirement_type",models.CharField(choices=[("modules","Modules"),("final_quiz","Final quiz"),("assignments","Assignments"),("labs","Labs")],max_length=30)),("required",models.BooleanField(default=True)),("minimum_score",models.PositiveSmallIntegerField(default=80)),("course",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="completion_requirements",to="academy.academycourse"))]),
        migrations.CreateModel(name="CourseAnnouncement",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("title",models.CharField(max_length=255)),("message",models.TextField()),("scheduled_for",models.DateTimeField(blank=True,null=True)),("published",models.BooleanField(default=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("created_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),("course",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="announcements",to="academy.academycourse"))]),
        migrations.AddConstraint(model_name="courseenrollment",constraint=models.UniqueConstraint(fields=("user","course"),name="academy_unique_course_enrollment")),
    ]
