# Generated by Django 6.0.8 on 2026-08-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_module_certificates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['country', 'title']},
        ),
        migrations.AlterModelOptions(
            name='courseenrollment',
            options={'ordering': ['-enrolled_at']},
        ),
        migrations.AlterModelOptions(
            name='courseversion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='discussionpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='learningrecord',
            options={'ordering': ['-occurred_at']},
        ),
        migrations.AlterModelOptions(
            name='livesession',
            options={'ordering': ['starts_at']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['level__number', 'pathway_id', 'order']},
        ),
        migrations.AlterField(
            model_name='certificatesettings',
            name='signature_credentials',
            field=models.CharField(default='PhD, [FIELD]', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificatesettings',
            name='signature_name',
            field=models.CharField(default='Prof. Dr. [NAME]', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificatesettings',
            name='signature_title',
            field=models.CharField(default='Academic Director / Academic Advisor', max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosticattempt',
            name='answers',
            field=models.JSONField(default=dict),
        ),
    ]
