import { useRouter } from 'next/router'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import ApplicationShell from '../../../components/ApplicationShell'
import api from '../../../utils/api'

export default function ModulePage(){
  const router=useRouter(); const id=router.query.id
  const [data,setData]=useState<any>(null),[answers,setAnswers]=useState<Record<string,string[]>>({}),[questions,setQuestions]=useState<any[]>([])
  const [completedLessons,setCompletedLessons]=useState<Record<string,boolean>>({}),[completed,setCompleted]=useState(false)
  const [certificateId,setCertificateId]=useState(''),[badges,setBadges]=useState<any[]>([]),[next,setNext]=useState<any>(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)

  function randomize(qs:any[]){ const a=[...qs]; for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]} return a.slice(0,Math.min(6,a.length)) }

  async function load(){ if(!id)return; setError(''); try{ const r=await api.get(`/academy/modules/${id}/`); setData(r.data); setQuestions(randomize(r.data.quiz?.questions||[])); const initial:any={}; (r.data.lessons||[]).forEach((l:any)=>{if(l.completed||l.completed_at)initial[l.id]=true}); setCompletedLessons(initial) }catch(e:any){setError(e?.response?.data?.detail||'Unable to load module.')} }
  useEffect(()=>{load()},[id])

  async function markLesson(lesson:any){setBusy(true); try{const r=await api.post(`/academy/lessons/${lesson.id}/complete/`);setCompletedLessons(x=>({...x,[lesson.id]:true}));setMessage('✓ Lesson completed and progress saved.')}catch(e:any){setMessage(e?.response?.data?.detail||'Could not save lesson progress.')}finally{setBusy(false)}}

  async function submit(){if(!data?.quiz)return; setBusy(true); try{const r=await api.post(`/academy/quizzes/${data.quiz.id}/submit/`,{answers}); if(!r.data.passed){setMessage(`${r.data.score}% — not yet passed. Try a new question set.`);return} const c=r.data.completion; if(c?.completed){setCompleted(true);setCertificateId(c.certificate_id||'');setBadges(c.badges||[]);setNext(c.next_module||null);setMessage(`✓ ${r.data.score}% — module completed. Your certificate is ready.`)} else {setMessage(c?.message||'Assessment passed. Finish any remaining required activity.')} }catch(e:any){setMessage(e?.response?.data?.detail||'Could not submit assessment.')}finally{setBusy(false)}}

  function newSet(){setQuestions(randomize(data?.quiz?.questions||[]));setAnswers({});setMessage('New question set generated.')} 
  async function download(path:string,name:string){try{const r=await api.get(path,{responseType:'blob'});const url=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}catch(e:any){setMessage(e?.response?.data?.detail||'Download failed.')}}

  if(error)return <ApplicationShell name="Research Academy" description="Learning module" nav={[["/research-academy","Academy"],["/research-academy/certificates","Certificates"]]}><main className="mx-auto max-w-3xl px-4 py-10"><div className="rounded-3xl bg-rose-50 p-6 text-rose-900"><h1 className="text-2xl font-black">Module unavailable</h1><p className="mt-2">{error}</p><Link href="/research-academy" className="mt-5 inline-flex rounded-xl bg-slate-950 px-4 py-2.5 font-black text-white">Back to Academy</Link></div></main></ApplicationShell>
  if(!data)return <ApplicationShell name="Research Academy" description="Learning module" nav={[["/research-academy","Academy"]]}><main className="mx-auto max-w-4xl px-4 py-10">Loading module…</main></ApplicationShell>

  const required=(data.lessons||[]).filter((l:any)=>l.required!==false); const allDone=required.every((l:any)=>completedLessons[l.id]);
  return <ApplicationShell name="Research Academy" description="Learning module" nav={[["/research-academy","Academy"],["/research-academy/dashboard","My Learning"],["/research-academy/certificates","Certificates"]]}>
    <main className="mx-auto max-w-5xl px-4 pb-16">
      <section className="rounded-3xl bg-slate-950 p-6 text-white sm:p-8"><div className="text-xs font-black uppercase tracking-widest text-emerald-300">Level {data.level}</div><h1 className="mt-2 text-3xl font-black sm:text-4xl">{data.title}</h1><p className="mt-3 max-w-3xl leading-7 text-slate-300">{data.summary}</p></section>
      <section className="mt-5 rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="text-xl font-black">Learning objectives</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{(data.objectives||[]).map((x:string)=><div key={x} className="rounded-2xl bg-slate-50 p-4 text-sm font-semibold">✓ {x}</div>)}</div></section>
      {(data.lessons||[]).map((lesson:any)=><article key={lesson.id} className="mt-5 rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><div className="text-xs font-black uppercase tracking-widest text-emerald-700">Lesson {lesson.order}</div><h2 className="mt-2 text-2xl font-black">{lesson.title}</h2><div className="mt-4 whitespace-pre-line leading-7 text-slate-700">{lesson.body}</div>{lesson.video_url&&<a href={lesson.video_url} target="_blank" rel="noreferrer" className="mt-4 inline-flex rounded-xl bg-slate-100 px-4 py-2.5 text-sm font-black">Open optional video ↗</a>}<button disabled={busy||completedLessons[lesson.id]} onClick={()=>markLesson(lesson)} className="mt-5 rounded-xl bg-emerald-600 px-4 py-3 text-sm font-black text-white disabled:opacity-50">{completedLessons[lesson.id]?'✓ Lesson completed':'Mark lesson complete'}</button></article>)}
      {data.quiz&&<section className="mt-5 rounded-3xl bg-white p-5 shadow-sm ring-1 ring-violet-100 sm:p-7"><div className="text-xs font-black uppercase tracking-widest text-violet-700">Assessment · Pass {data.quiz.pass_mark}%</div><h2 className="mt-2 text-2xl font-black">{data.quiz.title}</h2><p className="mt-2 text-sm text-slate-600">This is a foundation check. A new question set can be generated for another attempt.</p><button onClick={newSet} className="mt-4 rounded-xl border border-violet-200 px-3 py-2 text-xs font-black text-violet-800">New question set</button><div className="mt-5 space-y-4">{questions.map((q:any,i:number)=><div key={q.id} className="rounded-2xl border border-slate-200 p-4"><div className="font-black">{i+1}. {q.prompt}</div><div className="mt-3 space-y-2">{q.choices.map((c:any)=><label key={c.id} className="flex gap-3 rounded-xl border p-3 text-sm"><input type="radio" name={`q-${q.id}`} checked={(answers[q.id]||[]).includes(String(c.id))} onChange={()=>setAnswers({...answers,[q.id]:[String(c.id)]})}/><span>{c.text}</span></label>)}</div></div>)}</div><button onClick={submit} disabled={busy||!questions.length||Object.keys(answers).length!==questions.length} className="mt-6 w-full rounded-xl bg-violet-700 px-5 py-3 font-black text-white disabled:opacity-50">{busy?'Processing…':'Submit assessment'}</button></section>}
      {(completed||certificateId)&&<section className="mt-5 rounded-3xl border border-emerald-200 bg-emerald-50 p-5 sm:p-7"><div className="text-xs font-black uppercase tracking-widest text-emerald-800">Module completed</div><h2 className="mt-2 text-2xl font-black text-slate-950">Your achievement is ready.</h2><p className="mt-2 text-sm leading-6 text-slate-700">Your completion has been recorded. The certificate and badge are now part of your Academy credentials.</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><button onClick={()=>download(`/academy/modules/${data.id}/download/`,`${data.slug||'module'}-pack.pdf`)} className="rounded-2xl bg-slate-950 p-4 text-left text-sm font-black text-white">Download module + assessment</button>{certificateId?<button onClick={()=>download(`/academy/certificates/${certificateId}/download/`,`${certificateId}.pdf`)} className="rounded-2xl bg-white p-4 text-left text-sm font-black text-slate-950 ring-1 ring-emerald-300">Download certificate</button>:<Link href="/research-academy/certificates" className="rounded-2xl bg-white p-4 text-left text-sm font-black text-slate-950 ring-1 ring-emerald-300">Open certificates</Link>}<Link href="/research-academy/certificates" className="rounded-2xl bg-emerald-600 p-4 text-left text-sm font-black text-white">View badges & credentials</Link></div>{next?.unlocked&&<div className="mt-5 rounded-2xl bg-white p-4"><div className="text-xs font-black uppercase tracking-widest text-emerald-700">Next module unlocked</div><div className="mt-1 font-black text-slate-950">{next.title}</div><Link href={next.url} className="mt-3 inline-flex rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-black text-white">Continue →</Link></div>}</section>}
      {message&&<div className="sticky bottom-4 mt-5 rounded-2xl bg-slate-950 p-4 text-center text-sm font-bold text-white">{message}</div>}
    </main>
  </ApplicationShell>
}
