from django.urls import path
from .views import (
    AcademyOverviewView, ModuleDetailView, EnrollmentView,
    CompleteLessonView, SubmitQuizView, CertificateListView,
    CertificateVerifyView,
    AcademyAdminDashboardView, CourseEnrollmentView, LearningDashboardView, CourseAnnouncementView, AdminCourseAnnouncementView, AcademyAdminCoursesView, AcademyAdminLevelDetailView,
    AcademyAdminModuleView, AcademyAdminLessonView, AcademyAdminQuizView, AcademyAdminQuestionView,
    StudentQuestionView, AcademyAdminStudentsView, AcademyAdminQuestionsView, AcademyAdminQuestionReplyView,
    AcademyAdminCertificateSettingsView, AcademyEnhancementsView, DiagnosticAssessmentView, PracticeLabView, PracticeLabGenerateQuestionsView, DiscussionView, AIResearchCoachView, ReportingGuidelineWizardView, AcademyAdminEnhancementsView, CohortListView, CohortDetailView, CourseListView, CourseDetailView, AssignmentSubmitView, MyAssignmentSubmissionsView, AdminAssignmentView, AdminAssignmentGradeView, AdminPrerequisiteView, LabSubmitView, AdminLabGradeView,
)

urlpatterns = [
    path("", AcademyOverviewView.as_view(), name="academy-overview"),
    path("enrollment/", EnrollmentView.as_view(), name="academy-enrollment"),
    path("courses/", CourseListView.as_view(), name="academy-courses"),
    path("courses/<int:pk>/", CourseDetailView.as_view(), name="academy-course"),
    path("courses/<int:pk>/enroll/", CourseEnrollmentView.as_view(), name="academy-course-enroll"),
    path("courses/<int:pk>/announcements/", CourseAnnouncementView.as_view(), name="academy-course-announcements"),
    path("my-enrollments/", CourseEnrollmentView.as_view(), name="academy-my-enrollments"),
    path("my-learning/", LearningDashboardView.as_view(), name="academy-my-learning"),
    path("admin/courses/<int:pk>/announcements/", AdminCourseAnnouncementView.as_view(), name="academy-admin-course-announcement"),
    path("assignments/<int:pk>/submit/", AssignmentSubmitView.as_view(), name="academy-assignment-submit"),
    path("assignments/my/", MyAssignmentSubmissionsView.as_view(), name="academy-my-assignments"),
    path("admin/assignments/", AdminAssignmentView.as_view(), name="academy-admin-assignment"),
    path("admin/assignments/submissions/<int:pk>/grade/", AdminAssignmentGradeView.as_view(), name="academy-admin-assignment-grade"),
    path("admin/prerequisites/", AdminPrerequisiteView.as_view(), name="academy-admin-prerequisite-create"),
    path("admin/prerequisites/<int:pk>/", AdminPrerequisiteView.as_view(), name="academy-admin-prerequisite-delete"),
    path("modules/<int:pk>/", ModuleDetailView.as_view(), name="academy-module"),
    path("lessons/<int:pk>/complete/", CompleteLessonView.as_view(), name="academy-lesson-complete"),
    path("quizzes/<int:pk>/submit/", SubmitQuizView.as_view(), name="academy-quiz-submit"),
    path("certificates/", CertificateListView.as_view(), name="academy-certificates"),
    path("cohorts/", CohortListView.as_view(), name="academy-cohorts"),
    path("cohorts/<int:pk>/", CohortDetailView.as_view(), name="academy-cohort-detail"),
    path("certificates/verify/<str:certificate_id>/", CertificateVerifyView.as_view(), name="academy-certificate-verify"),
    path("questions/", StudentQuestionView.as_view(), name="academy-student-questions"),
    path("admin/", AcademyAdminDashboardView.as_view(), name="academy-admin-dashboard"),
    path("admin/courses/", AcademyAdminCoursesView.as_view(), name="academy-admin-courses"),
    path("admin/levels/<int:pk>/", AcademyAdminLevelDetailView.as_view(), name="academy-admin-level"),
    path("admin/modules/", AcademyAdminModuleView.as_view(), name="academy-admin-module-create"),
    path("admin/modules/<int:pk>/", AcademyAdminModuleView.as_view(), name="academy-admin-module"),
    path("admin/lessons/", AcademyAdminLessonView.as_view(), name="academy-admin-lesson-create"),
    path("admin/lessons/<int:pk>/", AcademyAdminLessonView.as_view(), name="academy-admin-lesson"),
    path("admin/quizzes/<int:pk>/", AcademyAdminQuizView.as_view(), name="academy-admin-quiz"),
    path("admin/questions/", AcademyAdminQuestionView.as_view(), name="academy-admin-question-create"),
    path("admin/questions/<int:pk>/", AcademyAdminQuestionView.as_view(), name="academy-admin-question"),
    path("admin/students/", AcademyAdminStudentsView.as_view(), name="academy-admin-students"),
    path("admin/questions/support/", AcademyAdminQuestionsView.as_view(), name="academy-admin-support-questions"),
    path("admin/questions/support/<int:pk>/", AcademyAdminQuestionReplyView.as_view(), name="academy-admin-support-question"),
    path("admin/certificate-settings/", AcademyAdminCertificateSettingsView.as_view(), name="academy-admin-certificate-settings"),
    path("enhancements/", AcademyEnhancementsView.as_view(), name="academy-enhancements"),
    path("diagnostic/", DiagnosticAssessmentView.as_view(), name="academy-diagnostic"),
    path("labs/<int:pk>/", PracticeLabView.as_view(), name="academy-lab"),
    path("labs/<int:pk>/submit/", LabSubmitView.as_view(), name="academy-lab-submit"),
    path("labs/<int:pk>/generate-questions/", PracticeLabGenerateQuestionsView.as_view(), name="academy-lab-generate-questions"),
    path("admin/labs/submissions/<int:pk>/grade/", AdminLabGradeView.as_view(), name="academy-admin-lab-grade"),
    path("discussion/<int:module_id>/", DiscussionView.as_view(), name="academy-discussion"),
    path("ai-coach/", AIResearchCoachView.as_view(), name="academy-ai-coach"),
    path("guideline-wizard/", ReportingGuidelineWizardView.as_view(), name="academy-guideline-wizard"),
    path("admin/enhancements/", AcademyAdminEnhancementsView.as_view(), name="academy-admin-enhancements"),
]
