from pathlib import Path

root=Path('/mnt/data/v35work/backend')

# 1) Add cross-pillar integration helpers to shared services.
p=root/'rsre_core/services.py'
s=p.read_text()
insert='''\n\ndef record_passport_evidence(user, evidence_type, title, description, source_model, source_object_id, evidence_date=None, metadata=None):\n    """Idempotently append verified RSRE activity to the Research Passport."""\n    if not user or not getattr(user, "is_authenticated", False):\n        return None\n    from journal.models import PassportEvidence\n    from django.utils import timezone as _timezone\n    obj, _ = PassportEvidence.objects.get_or_create(\n        user=user,\n        evidence_type=evidence_type,\n        source_model=source_model,\n        source_object_id=str(source_object_id),\n        defaults={\n            "title": title,\n            "description": description,\n            "source_type": "automatic",\n            "evidence_date": evidence_date or _timezone.now().date(),\n            "verification_code": f"RSRE-{user.pk}-{source_model}-{source_object_id}",\n            "verified_at": _timezone.now(),\n            "active": True,\n        },\n    )\n    if metadata and obj.description == description:\n        pass\n    return obj\n\n\ndef emit_research_event(user, *, subject, message, event_key, application_key, action_url="/dashboard", evidence=None, whatsapp_text=None):\n    """Single entry point for cross-pillar momentum: notification + optional Passport evidence."""\n    if evidence:\n        record_passport_evidence(user, **evidence)\n    return dispatch_notification(\n        user, subject, message, event_key=event_key,\n        application_key=application_key, action_url=action_url,\n        whatsapp_text=whatsapp_text,\n    )\n'''
if 'def record_passport_evidence(' not in s:
    s=s.replace('\ndef create_whatsapp_group', insert+'\ndef create_whatsapp_group')
p.write_text(s)

# 2) Fix journal Passport integration to match actual PassportEvidence schema.
p=root/'journal/integrations/passport.py'
s=p.read_text()
s='''"""Non-destructive RSJH -> Research Passport integration."""\nfrom rsre_core.services import record_passport_evidence\n\n\ndef record_manuscript_submission(article):\n    return record_passport_evidence(\n        article.author, "publication", f"RSJH manuscript submitted: {article.title}",\n        "A manuscript was successfully submitted to the Rwanda Student Journal for Health.",\n        "journal.article", article.pk, metadata={"journal":"RSJH","event":"submitted"},\n    )\n\n\ndef record_peer_review(review):\n    return record_passport_evidence(\n        review.reviewer, "review", f"RSJH peer review completed: {review.article.title}",\n        "A peer review was successfully completed for an RSJH manuscript.",\n        "journal.review", review.pk, metadata={"journal":"RSJH","event":"review_completed"},\n    )\n\n\ndef record_publication(article):\n    return record_passport_evidence(\n        article.author, "publication", f"RSJH publication: {article.title}",\n        "A manuscript reached publication in RSJH and was recorded as research evidence.",\n        "journal.article.publication", article.pk, metadata={\n            "journal":"RSJH","event":"published","doi":article.doi,\n            "publication_number":article.publication_number,"volume":article.volume,"issue":article.issue,\n        },\n    )\n'''
p.write_text(s)

# 3) Academy: certificate notifications + Passport evidence for module/level/pathway and course completion.
p=root/'academy/services.py'
s=p.read_text()
s=s.replace('from .models import LevelCertificate, PathwayCertificate, ModuleCertificate, CertificateSettings', 'from .models import LevelCertificate, PathwayCertificate, ModuleCertificate, CertificateSettings')
old='''    cert, _ = LevelCertificate.objects.get_or_create(\n        user=user, level=level,\n        defaults={"certificate_id": f"RSRE-RA-L{level.number}-{timezone.now().year}-{user.pk:05d}"},\n    )\n    return cert\n'''
new='''    cert, created = LevelCertificate.objects.get_or_create(\n        user=user, level=level,\n        defaults={"certificate_id": f"RSRE-RA-L{level.number}-{timezone.now().year}-{user.pk:05d}"},\n    )\n    if created:\n        from rsre_core.services import emit_research_event\n        emit_research_event(\n            user, subject="Research Academy — level certificate earned",\n            message=f"Congratulations. You completed Level {level.number}: {level.name}. Certificate {cert.certificate_id} is now available.",\n            event_key="academy_level_certificate", application_key="academy",\n            action_url=f"/research-academy/certificate/{cert.certificate_id}",\n            evidence={"evidence_type":"credential","title":f"Academy Level {level.number} certificate: {level.name}","description":"Research Academy level certificate earned.","source_model":"academy.level_certificate","source_object_id":cert.pk},\n        )\n    return cert\n'''
s=s.replace(old,new)
old='''    cert, _ = PathwayCertificate.objects.get_or_create(\n        user=user, pathway=pathway,\n        defaults={"certificate_id": f"RSRE-RA-SP-{pathway.code[:8].upper()}-{timezone.now().year}-{user.pk:05d}"},\n    )\n    return cert\n'''
new='''    cert, created = PathwayCertificate.objects.get_or_create(\n        user=user, pathway=pathway,\n        defaults={"certificate_id": f"RSRE-RA-SP-{pathway.code[:8].upper()}-{timezone.now().year}-{user.pk:05d}"},\n    )\n    if created:\n        from rsre_core.services import emit_research_event\n        emit_research_event(\n            user, subject="Research Academy — pathway certificate earned",\n            message=f"Congratulations. You completed the {pathway.name} pathway. Certificate {cert.certificate_id} is now available.",\n            event_key="academy_pathway_certificate", application_key="academy",\n            action_url=f"/research-academy/certificate/{cert.certificate_id}",\n            evidence={"evidence_type":"credential","title":f"Academy pathway certificate: {pathway.name}","description":"Research Academy specialist pathway certificate earned.","source_model":"academy.pathway_certificate","source_object_id":cert.pk},\n        )\n    return cert\n'''
s=s.replace(old,new)
old='''        record_learning_event(user,"course_completed",course.title,"course",course.id,{"course_code":course.code})\n        notify_academy(user,"Research Academy — course completed",f"You completed {course.title}.",f"/research-academy/course/{course.id}","View course")\n'''
new='''        record_learning_event(user,"course_completed",course.title,"course",course.id,{"course_code":course.code})\n        from rsre_core.services import emit_research_event\n        emit_research_event(\n            user, subject="Research Academy — course completed",\n            message=f"You completed {course.title}. Your next research-learning step is ready.",\n            event_key="academy_course_completed", application_key="academy",\n            action_url=f"/research-academy/course/{course.id}",\n            evidence={"evidence_type":"learning","title":f"Academy course completed: {course.title}","description":"Research Academy course completed.","source_model":"academy.course_completion","source_object_id":f"{course.id}-{user.pk}"},\n        )\n'''
s=s.replace(old,new)
p.write_text(s)

# 4) Journal project milestones: update endpoint + notifications/evidence; project advancement notification.
p=root/'journal/views.py'
s=p.read_text()
needle='''    @action(detail=True, methods=["post"], url_path="advance")\n    def advance(self, request, pk=None):\n'''
insert='''    @action(detail=True, methods=["post"], url_path="update-milestone")\n    def update_milestone(self, request, pk=None):\n        project = self.get_object()\n        if not self._can_manage(project):\n            raise PermissionDenied("Only the project owner or an administrator can update milestones.")\n        try:\n            milestone = project.milestones.get(pk=request.data.get("milestone_id"))\n        except ResearchProjectMilestone.DoesNotExist:\n            return Response({"detail":"Milestone not found."}, status=404)\n        allowed = {"title", "description", "due_date", "status", "order"}\n        changes = {k:v for k,v in request.data.items() if k in allowed}\n        if "status" in changes and changes["status"] not in {c[0] for c in ResearchProjectMilestone.STATUS_CHOICES}:\n            return Response({"detail":"Invalid milestone status."}, status=400)\n        was_done = milestone.status == "done"\n        for key, value in changes.items():\n            setattr(milestone, key, value)\n        milestone.save()\n        if milestone.status == "done" and not was_done:\n            from rsre_core.services import emit_research_event\n            emit_research_event(\n                project.owner, subject="RSRE — research milestone completed",\n                message=f"Milestone completed: {milestone.title} in {project.title}. Your next project action is now ready.",\n                event_key="incubator_milestone_completed", application_key="incubator",\n                action_url=f"/incubator/{project.id}",\n                evidence={"evidence_type":"milestone","title":f"Research milestone: {milestone.title}","description":f"Completed milestone in research project: {project.title}.","source_model":"journal.research_project_milestone","source_object_id":milestone.pk},\n            )\n            for member in project.members.filter(status="active").select_related("user"):\n                if member.user_id != project.owner_id:\n                    emit_research_event(member.user, subject="RSRE — project milestone completed", message=f"{milestone.title} was completed in {project.title}.", event_key="incubator_milestone_team_update", application_key="incubator", action_url=f"/incubator/{project.id}")\n        return Response(ResearchProjectMilestoneSerializer(milestone).data)\n\n'''
if needle in s and 'def update_milestone' not in s:
    s=s.replace(needle, insert+needle)
old='''        project.status = next_status; project.save(update_fields=["status", "updated_at"])\n        return Response(ResearchProjectSerializer(project, context={"request": request}).data)\n'''
new='''        project.status = next_status; project.save(update_fields=["status", "updated_at"])\n        from rsre_core.services import emit_research_event\n        emit_research_event(\n            project.owner, subject="RSRE — research project stage updated",\n            message=f"{project.title} moved to {project.get_status_display()}. Review the next recommended action in your project cockpit.",\n            event_key="incubator_stage_updated", application_key="incubator", action_url=f"/incubator/{project.id}",\n        )\n        return Response(ResearchProjectSerializer(project, context={"request": request}).data)\n'''
s=s.replace(old,new)
p.write_text(s)

# 5) StudentGift migration cleanup: remove journal_support from future schema.
mp=root/'journal/migrations/0022_remove_journal_support_gift_purpose.py'
mp.write_text('''from django.db import migrations, models\n\nclass Migration(migrations.Migration):\n    dependencies = [("journal", "0021_student_gift")]\n    operations = [\n        migrations.AlterField(\n            model_name="studentgift",\n            name="purpose",\n            field=models.CharField(\n                choices=[\n                    ("academy_support", "Research Academy Support"),\n                    ("research_support", "Research Development Support"),\n                    ("general", "General RSRE Gift"),\n                ],\n                default="general", max_length=30,\n            ),\n        ),\n    ]\n''')
# Add a forward cleanup note in docs.
(root/'docs'/'RSRE_CROSS_PILLAR_INTEGRATION_V35.md').write_text('''# RSRE V35 — Cross-Pillar Integration\n\nV35 adds the shared momentum/event layer without replacing pillar workflows.\n\n## Integrated events\n- Academy module/level/pathway certificates -> Passport evidence + in-app/email/WhatsApp hooks\n- Academy course completion -> Passport learning evidence + next-step notification\n- Incubator milestone completion -> Passport milestone evidence + owner/team notifications\n- Incubator stage changes -> next-action notification\n- RSJH submission/review/publication -> Passport evidence through the protected journal integration\n- Collaboration request lifecycle -> shared notifications\n\n## Protection\n- RSJH remains free.\n- Editorial state machine is unchanged.\n- Sponsorship cannot represent publication payment.\n- WhatsApp credentials are not stored in the package; deployment configuration happens later.\n\n## Remaining deployment step\nConfigure the WhatsApp provider, email provider, payment provider (for sponsor-side support only), background job runner and production secrets on the deployment environment.\n''')

# Update contract doc.
contract=root.parent/'docs/RSRE_PLATFORM_NOTIFICATION_CONTRACT.md'
if contract.exists():
    text=contract.read_text()
    if 'V35 cross-pillar event layer' not in text:
        text += '\n\n## V35 cross-pillar event layer\nCertificate, milestone, publication and collaboration events can now append Passport evidence and dispatch a shared momentum notification. WhatsApp remains opt-in and deployment-configured.\n'
        contract.write_text(text)

