import { FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/router'
import api from '../../utils/api'

const tabs=[['overview','Overview'],['applications','Applications'],['journal','RSJH Journal'],['platform','Global Content'],['support','Support'],['communications','Communications'],['settings','Settings'],['audit','Audit']]

const pillarAdmin=[
  ['Research Academy','Curriculum, modules, lessons, assessments and certificates.','/research-academy/admin','44+ modules can be edited here.'],
  ['Research Discovery','Scholarly search, local research and evidence exploration.','/research-discovery','Search and discover research.'],
  ['Research Opportunities','Funding, scholarships, fellowships, internships and calls.','/research-opportunities','Live opportunity feed.'],
  ['Research Incubator','Ideas, projects, teams, milestones and governance.','/research-incubator','Build real studies.'],
  ['Research Sandbox','Private experimentation, datasets, notebooks and reproducibility.','/research-sandbox','Safe research workbench.'],
  ['Research Passport','Competencies, evidence, credentials and verification.','/research-passport','Build the research record.'],
  ['Collaboration Network','Research matching, mentorship and purposeful connection.','/collaboration','Find the right people.'],
  ['Ethics & Compliance','Research governance readiness and integrity guidance.','/ethics-compliance','Prepare studies responsibly.'],
  ['MedTech AI','Responsible AI support for research work.','/medtech-ai','AI remains human-supervised.'],
]

export default function AdminCenter(){
  const router=useRouter()
  const [tab,setTab]=useState('overview')
  const [stats,setStats]=useState<any>(null),[apps,setApps]=useState<any[]>([]),[content,setContent]=useState<any[]>([]),[support,setSupport]=useState<any[]>([]),[notifications,setNotifications]=useState<any[]>([]),[audit,setAudit]=useState<any[]>([]),[settings,setSettings]=useState<any>({}),[message,setMessage]=useState('')
  const [contentForm,setContentForm]=useState({application:'',slug:'',title:'',content_type:'announcement',body:'',order:'0'})
  const [invitation,setInvitation]=useState({role:'reviewer',contact_name:'',email:'',organization:''})
  const [invitationResult,setInvitationResult]=useState('')

  function selectTab(next:string){setTab(next);router.replace({pathname:'/rsre-admin',query:{tab:next}},undefined,{shallow:true})}
  async function load(){
    const results=await Promise.allSettled([api.get('/rsre/admin/dashboard/'),api.get('/rsre/admin/applications/'),api.get('/rsre/admin/content/'),api.get('/rsre/admin/support/'),api.get('/rsre/admin/notifications/'),api.get('/rsre/admin/audit/'),api.get('/rsre/admin/settings/')])
    const [d,a,c,s,n,au,st]=results
    if(d.status==='fulfilled') setStats(d.value.data)
    if(a.status==='fulfilled') setApps(a.value.data||[])
    if(c.status==='fulfilled') setContent(c.value.data||[])
    if(s.status==='fulfilled') setSupport(s.value.data||[])
    if(n.status==='fulfilled') setNotifications(n.value.data||[])
    if(au.status==='fulfilled') setAudit(au.value.data||[])
    if(st.status==='fulfilled') setSettings(st.value.data||{})
  }
  useEffect(()=>{const q=typeof router.query.tab==='string'?router.query.tab:'overview';setTab(tabs.some(([k])=>k===q)?q:'overview')},[router.query.tab])
  useEffect(()=>{load()},[])

  async function saveSettings(e:FormEvent){e.preventDefault();try{const r=await api.put('/rsre/admin/settings/',settings);setSettings(r.data);setMessage('Platform settings saved.')}catch(e:any){setMessage(e?.response?.data?.detail||'Could not save settings.')}}
  async function toggleApp(app:any){try{await api.put(`/rsre/admin/applications/${app.id}/`,{active:!app.active});await load();setMessage(`${app.name} is now ${app.active?'disabled':'active'}.`)}catch(e:any){setMessage(e?.response?.data?.detail||'Could not update application.')}}
  async function createContent(e:FormEvent){e.preventDefault();try{await api.post('/rsre/admin/content/',{...contentForm,application:Number(contentForm.application),order:Number(contentForm.order)});setContentForm({application:'',slug:'',title:'',content_type:'announcement',body:'',order:'0'});await load();setMessage('Platform content created.')}catch(e:any){setMessage(e?.response?.data?.detail||'Could not create content.')}}
  async function deleteContent(id:number){if(!confirm('Delete this platform content item?'))return;try{await api.delete(`/rsre/admin/content/${id}/`);await load()}catch(e:any){setMessage(e?.response?.data?.detail||'Could not delete content.')}}
  async function updateSupport(id:number,status:string){try{await api.put(`/rsre/admin/support/${id}/`,{status});await load();setMessage('Support ticket updated.')}catch(e:any){setMessage(e?.response?.data?.detail||'Could not update support ticket.')}}
  async function replySupport(id:number){const body=prompt('Reply to the support ticket:');if(!body?.trim())return;try{await api.post(`/rsre/admin/support/${id}/reply/`,{message:body.trim()});await load();setMessage('Support reply sent.')}catch(e:any){setMessage(e?.response?.data?.detail||'Could not reply.')}}
  async function sendInvitation(e:FormEvent){e.preventDefault();try{const r=await api.post('/reviewer-invitations/',invitation);setInvitationResult(`Invitation sent: ${r.data?.code||'created'}`);setInvitation({role:'reviewer',contact_name:'',email:'',organization:''})}catch(e:any){setInvitationResult(e?.response?.data?.detail||'Invitation could not be sent.')}}
  function logout(){if(typeof window==='undefined')return;['rmsjToken','rmsjRefresh','rmsjRefreshToken','rmsjRole','rmsjUsername','rmsjFullName','rmsjUser'].forEach(k=>localStorage.removeItem(k));window.dispatchEvent(new Event('rmsj-auth-changed'));window.location.href='/'}

  const pub=stats?.journal_articles||0
  return <main className="min-h-screen bg-slate-100"><header className="sticky top-0 z-40 border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-[1500px] flex-wrap items-center justify-between gap-4 px-4 py-4 sm:px-6 lg:px-8"><Link href="/" className="flex items-center gap-3"><img src="/logo.png" alt="RSRE" className="h-11 w-11 rounded-2xl object-contain"/><div><div className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">RSRE Control Center</div><div className="font-black text-slate-950">Whole-ecosystem administration</div></div></Link><nav className="flex flex-wrap items-center gap-2"><Link href="/" className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold">Home</Link><Link href="/articles" className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold">RSJH Journal</Link><Link href="/about" className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold">About</Link><button onClick={logout} className="rounded-xl bg-rose-50 px-3 py-2 text-xs font-black text-rose-700">Logout</button></nav></div></header>
    <div className="mx-auto max-w-[1500px] px-4 py-8 sm:px-6 lg:px-8"><div><div className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">Administrator Workspace</div><h1 className="mt-2 text-4xl font-black">One dashboard. The whole ecosystem.</h1><p className="mt-3 max-w-3xl text-slate-600">The Control Center manages the platform itself. Each pillar keeps its own professional workspace and workflow.</p></div>
      {message&&<div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{message}</div>}
      <div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-6">{[['Users',stats?.users||0],['Applications',stats?.applications||0],['Academy modules',stats?.academy_modules||0],['Journal articles',pub],['Support open',stats?.support_open||0],['Failed notifications',stats?.notifications_failed||0]].map(([n,v])=><div key={String(n)} className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="text-3xl font-black">{v}</div><div className="mt-1 text-sm text-slate-500">{n}</div></div>)}</div>
      <div className="mt-8 grid gap-6 lg:grid-cols-[240px_1fr]"><aside className="rounded-3xl bg-slate-950 p-4 text-white"><div className="space-y-1">{tabs.map(([k,label])=><button key={k} onClick={()=>selectTab(k)} className={`block w-full rounded-xl px-3 py-2 text-left text-sm font-bold ${tab===k?'bg-emerald-500 text-slate-950':'hover:bg-white/10'}`}>{label}</button>)}</div></aside><section className="min-w-0 rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200">
        {tab==='overview'&&<div><div className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">Architecture</div><h2 className="mt-2 text-3xl font-black">Distinct pillars, one research identity.</h2><p className="mt-2 max-w-3xl text-slate-500">Use this screen to enter a pillar. Do not turn every feature into a Control Center widget—the actual research work belongs in the pillar.</p><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{pillarAdmin.map(([title,text,href,meta])=><Link key={href} href={href} className="rounded-3xl border border-slate-200 p-5 hover:-translate-y-0.5 hover:shadow-lg"><div className="text-xs font-black uppercase tracking-wider text-emerald-700">Pillar</div><h3 className="mt-2 text-xl font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p><div className="mt-4 text-xs font-bold text-slate-400">{meta}</div><div className="mt-5 text-sm font-black text-emerald-700">Open workspace →</div></Link>)}</div><div className="mt-8 grid gap-4 md:grid-cols-2"><Link href="/dashboard/administrator" className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><div className="font-black text-blue-900">RSJH Editorial Administration</div><div className="mt-1 text-sm text-blue-800">Detailed manuscript, reviewer, editor, board, partner, founder and publication management.</div></Link><Link href="/research-academy/admin" className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div className="font-black text-emerald-900">Research Academy Administration</div><div className="mt-1 text-sm text-emerald-800">Build and edit levels, modules, lessons and assessments.</div></Link></div></div>}
        {tab==='applications'&&<div><h2 className="text-2xl font-black">Application control</h2><p className="mt-2 text-slate-500">Every core RSRE pillar is registered here with its own route. The button controls availability; the workspace link opens the actual application.</p><div className="mt-6 space-y-3">{apps.map(a=><div key={a.id} className="rounded-2xl border border-slate-200 p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-3"><span className="text-2xl">{a.icon}</span><div><div className="font-black text-slate-950">{a.name}</div><div className="text-xs text-slate-500">{a.route}</div></div></div><p className="mt-2 text-sm leading-6 text-slate-500">{a.description}</p></div><div className="flex flex-wrap gap-2">{a.route&&<Link href={a.route} className="rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-black text-white">Open module →</Link>}{a.key==='academy'&&<Link href="/research-academy/admin" className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2.5 text-xs font-black text-emerald-800">Admin</Link>}{a.key==='journal'&&<Link href="/dashboard/administrator" className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-2.5 text-xs font-black text-blue-800">Editorial Admin</Link>}<button onClick={()=>toggleApp(a)} className={`rounded-xl px-4 py-2.5 text-xs font-black ${a.active?'bg-amber-50 text-amber-800':'bg-emerald-50 text-emerald-800'}`}>{a.active?'Disable':'Enable'}</button></div></div></div>)}</div></div>}
        {tab==='journal'&&<div><div className="text-xs font-black uppercase tracking-[0.18em] text-blue-700">RSJH Journal</div><h2 className="mt-2 text-3xl font-black">Editorial operations</h2><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[['Manuscripts','/dashboard/administrator/manuscripts'],['Assign Reviewers','/dashboard/administrator/assign-reviewers'],['Editorial Board','/dashboard/administrator/editorial-board'],['Partners','/dashboard/administrator/partners'],['Founding Team','/dashboard/administrator/founding-team'],['Users','/dashboard/users'],['Journal Settings','/dashboard/administrator?tab=publication'],['Archive','/archive'],['Submit Manuscript','/submit']].map(([t,h])=><Link key={h} href={h} className="rounded-2xl border border-slate-200 p-5 hover:shadow-lg"><div className="font-black">{t}</div><div className="mt-3 text-xs font-black text-emerald-700">Open →</div></Link>)}</div><div className="mt-10 border-t border-slate-200 pt-8"><h3 className="text-2xl font-black">Invitations & Contacts</h3><p className="mt-2 text-sm text-slate-500">Invite reviewers, editors, Editor-in-Chief candidates and partners through the existing invitation service.</p><form onSubmit={sendInvitation} className="mt-5 grid gap-4 md:grid-cols-2"><select value={invitation.role} onChange={e=>setInvitation({...invitation,role:e.target.value})} className="rounded-xl border border-slate-200 px-4 py-3"><option value="reviewer">Reviewer</option><option value="editor">Editor</option><option value="editor_in_chief">Editor-in-Chief</option><option value="partner">Partner</option></select><input required placeholder="Contact name" value={invitation.contact_name} onChange={e=>setInvitation({...invitation,contact_name:e.target.value})} className="rounded-xl border border-slate-200 px-4 py-3"/><input required type="email" placeholder="Email" value={invitation.email} onChange={e=>setInvitation({...invitation,email:e.target.value})} className="rounded-xl border border-slate-200 px-4 py-3"/><input placeholder="Organization" value={invitation.organization} onChange={e=>setInvitation({...invitation,organization:e.target.value})} className="rounded-xl border border-slate-200 px-4 py-3"/><button className="w-fit rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white">Send invitation</button></form>{invitationResult&&<div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm font-bold">{invitationResult}</div>}</div></div>}
        {tab==='platform'&&<div><h2 className="text-2xl font-black">Global RSRE Content</h2><p className="mt-2 text-slate-500">Only global RSRE content lives here: announcements, banners, FAQs and shared platform notices. Academy, Incubator, Sandbox and RSJH content stays in its own pillar administration.</p><form onSubmit={createContent} className="mt-6 grid gap-4 md:grid-cols-2"><select required value={contentForm.application} onChange={e=>setContentForm({...contentForm,application:e.target.value})} className="rounded-xl border border-slate-200 px-4 py-3"><option value="">Choose pillar</option>{apps.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select value={contentForm.content_type} onChange={e=>setContentForm({...contentForm,content_type:e.target.value})} className="rounded-xl border border-slate-200 px-4 py-3"><option value="announcement">Announcement</option><option value="banner">Banner</option><option value="faq">FAQ</option><option value="page">Page</option><option value="resource">Resource</option></select><input required placeholder="Title" value={contentForm.title} onChange={e=>setContentForm({...contentForm,title:e.target.value})} className="rounded-xl border border-slate-200 px-4 py-3"/><input required placeholder="Slug" value={contentForm.slug} onChange={e=>setContentForm({...contentForm,slug:e.target.value})} className="rounded-xl border border-slate-200 px-4 py-3"/><input placeholder="Order" value={contentForm.order} onChange={e=>setContentForm({...contentForm,order:e.target.value})} className="rounded-xl border border-slate-200 px-4 py-3"/><textarea placeholder="Body" value={contentForm.body} onChange={e=>setContentForm({...contentForm,body:e.target.value})} className="md:col-span-2 min-h-32 rounded-xl border border-slate-200 px-4 py-3"/><button className="w-fit rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white">Create content</button></form><div className="mt-8 space-y-3">{content.map(c=><div key={c.id} className="flex flex-wrap items-start justify-between gap-4 rounded-2xl border border-slate-200 p-5"><div><div className="font-black">{c.title}</div><div className="text-xs text-slate-500">{c.content_type} · {c.slug}</div><p className="mt-2 text-sm text-slate-600">{c.body||'No body text.'}</p></div><button onClick={()=>deleteContent(c.id)} className="rounded-xl bg-rose-50 px-3 py-2 text-xs font-black text-rose-700">Delete</button></div>)}</div></div>}
        {tab==='support'&&<div><h2 className="text-2xl font-black">Support Desk</h2><p className="mt-2 text-slate-500">Manage user support without leaving the Control Center.</p><div className="mt-6 space-y-4">{support.map(t=><article key={t.id} className="rounded-2xl border border-slate-200 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="font-black">{t.subject}</div><div className="text-xs text-slate-500">{t.application_name||'RSRE'} · {t.priority} · {t.status}</div></div><div className="flex gap-2">{['new','in_progress','waiting','resolved','closed'].map(st=><button key={st} onClick={()=>updateSupport(t.id,st)} className="rounded-lg border border-slate-200 px-2 py-1 text-[10px] font-bold">{st.replace('_',' ')}</button>)}</div></div><p className="mt-3 text-sm leading-6 text-slate-600">{t.description}</p><button onClick={()=>replySupport(t.id)} className="mt-4 rounded-xl bg-slate-950 px-4 py-2 text-xs font-black text-white">Reply</button></article>)}{!support.length&&<div className="rounded-2xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">No support tickets.</div>}</div></div>}
        {tab==='communications'&&<div><h2 className="text-2xl font-black">Communications</h2><div className="mt-6 grid gap-4 md:grid-cols-3"><Metric label="Queued" value={stats?.notifications_queued||0}/><Metric label="Sent today" value={stats?.notifications_sent_today||0}/><Metric label="Failed" value={stats?.notifications_failed||0}/></div><div className="mt-7 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">User</th><th className="p-3">Channel</th><th className="p-3">Event</th><th className="p-3">Status</th></tr></thead><tbody>{notifications.slice(0,50).map(n=><tr key={n.id} className="border-b"><td className="p-3">{n.user}</td><td className="p-3">{n.channel}</td><td className="p-3">{n.event_key}</td><td className="p-3 font-bold">{n.status}</td></tr>)}</tbody></table></div></div>}
        {tab==='settings'&&<form onSubmit={saveSettings}><h2 className="text-2xl font-black">Platform Settings</h2><p className="mt-2 text-slate-500">Global identity and communication settings only.</p><div className="mt-6 grid gap-4 md:grid-cols-2">{Object.keys(settings).filter(k=>!['id','singleton_key','created_at','updated_at','whatsapp_token'].includes(k)).map(k=><label key={k} className="block"><span className="text-xs font-black capitalize text-slate-500">{k.replace(/_/g,' ')}</span>{typeof settings[k]==='boolean'?<input type="checkbox" checked={!!settings[k]} onChange={e=>setSettings({...settings,[k]:e.target.checked})} className="ml-3"/>:<input value={settings[k]??''} onChange={e=>setSettings({...settings,[k]:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-4 py-3"/>}</label>)}</div><button className="mt-6 rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white">Save settings</button></form>}
        {tab==='audit'&&<div><h2 className="text-2xl font-black">Audit & Governance</h2><div className="mt-6 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Actor</th><th className="p-3">Action</th><th className="p-3">Target</th><th className="p-3">Time</th></tr></thead><tbody>{audit.slice(0,100).map(a=><tr key={a.id} className="border-b"><td className="p-3">{a.actor}</td><td className="p-3 font-bold">{a.action}</td><td className="p-3">{a.target_type} {a.target_id}</td><td className="p-3 text-slate-500">{String(a.created_at||'').replace('T',' ').slice(0,19)}</td></tr>)}</tbody></table>{!audit.length&&<div className="p-8 text-center text-sm text-slate-500">No audit events recorded yet.</div>}</div></div>}
      </section></div>
    </div>
  </main>
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-slate-200 p-5"><div className="text-2xl font-black">{value}</div><div className="mt-1 text-sm text-slate-500">{label}</div></div>}
