import { useEffect, useState } from "react";
import Link from "next/link";
import DashboardLayout from "../../../components/DashboardLayout";
import api, { absoluteUrl } from "../../../utils/api";

type Member={id:number;name:string;role:string;biography?:string;photo?:string|null;display_order:number;active:boolean};
const empty={name:"",role:"",biography:"",display_order:1,active:true};
export default function FoundingTeam(){
 const [items,setItems]=useState<Member[]>([]); const [form,setForm]=useState(empty); const [photo,setPhoto]=useState<File|null>(null); const [editing,setEditing]=useState<number|null>(null); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
 const load=async()=>{try{const r=await api.get('/founding-members/');setItems(r.data?.results||r.data||[])}catch(e:any){setMessage(e?.response?.data?.detail||'Could not load founding team.')}};
 useEffect(()=>{load()},[]);
 function reset(){setForm(empty);setPhoto(null);setEditing(null);setMessage("");}
 async function save(e:any){e.preventDefault();setLoading(true);try{const fd=new FormData();Object.entries(form).forEach(([k,v])=>fd.append(k,String(v)));if(photo)fd.append('photo',photo);if(editing)await api.patch(`/founding-members/${editing}/`,fd);else await api.post('/founding-members/',fd);reset();setMessage(editing?'Profile updated.':'Profile added.');await load()}catch(e:any){setMessage(e?.response?.data?.detail||'Could not save profile.')}finally{setLoading(false)}}
 function edit(m:Member){setEditing(m.id);setForm({name:m.name,role:m.role,biography:m.biography||'',display_order:m.display_order,active:m.active});setPhoto(null);window.scrollTo({top:0,behavior:'smooth'});}
 async function remove(id:number){if(!confirm('Delete this founding-team profile?'))return;try{await api.delete(`/founding-members/${id}/`);await load();setMessage('Profile deleted.')}catch(e:any){setMessage(e?.response?.data?.detail||'Could not delete profile.')}}
 return <DashboardLayout role="administrator" roleRequired="administrator" title="Founding Team"><div className="space-y-8"><div><Link href="/dashboard/administrator" className="text-sm font-bold text-emerald-700">← Back to Administrator Dashboard</Link><h1 className="mt-3 text-3xl font-black">Founding Team</h1><p className="mt-2 text-slate-600">This is the single source for founding-team profiles shown on the public About page. Do not publish placeholder names.</p></div>
 <form onSubmit={save} className="bg-white rounded-3xl border border-violet-100 p-7 grid gap-4 md:grid-cols-2"><h2 className="md:col-span-2 text-xl font-black">{editing?'Edit profile':'Add founding member'}</h2><input required className="field" placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required className="field" placeholder="Role / title" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}/><textarea className="field min-h-32 md:col-span-2" placeholder="Verified biography" value={form.biography} onChange={e=>setForm({...form,biography:e.target.value})}/><input type="number" min="1" className="field" value={form.display_order} onChange={e=>setForm({...form,display_order:Number(e.target.value)||1})}/><label className="flex items-center gap-3 font-semibold"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Publish on About page</label><label className="md:col-span-2 block"><span className="font-semibold text-sm">Profile photo</span><input className="mt-2 block w-full" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setPhoto(e.target.files?.[0]||null)}/><span className="mt-1 block text-xs text-slate-500">Maximum 5 MB.</span></label><div className="md:col-span-2 flex flex-wrap gap-3"><button disabled={loading} className="rsjh-button-green">{loading?'Saving...':editing?'Save changes':'Add member'}</button>{editing&&<button type="button" onClick={reset} className="rounded-xl border px-5 py-3 font-bold">Cancel</button>}{message&&<span className="text-sm text-slate-600">{message}</span>}</div></form>
 <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{items.map(m=><article key={m.id} className="bg-white rounded-3xl border border-slate-200 p-6"><div className="h-48 rounded-2xl bg-slate-50 overflow-hidden flex items-center justify-center">{m.photo?<img src={absoluteUrl(m.photo)} alt={m.name} className="h-full w-full object-cover"/>:<span className="text-4xl font-black text-emerald-700">{m.name.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()}</span>}</div><h2 className="mt-5 text-xl font-black">{m.name}</h2><p className="mt-1 text-xs font-bold uppercase tracking-wide text-emerald-700">{m.role}</p>{m.biography&&<p className="mt-3 text-sm leading-6 text-slate-600">{m.biography}</p>}<div className="mt-5 flex gap-4"><button onClick={()=>edit(m)} className="text-sm font-bold text-blue-700">Edit</button><button onClick={()=>remove(m.id)} className="text-sm font-bold text-red-600">Delete</button></div></article>)}</div></div></DashboardLayout>
}
