# Generated by Django 6.0.7 on 2026-08-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_partner_options_alter_sponsor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['display_position', 'name']},
        ),
        migrations.AddField(
            model_name='sponsor',
            name='display_position',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
