# Generated by Django 6.0.7 on 2026-08-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_role_profiles_bookmarks_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={},
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='display_position',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='start_date',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision', 'Revision Required'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('accept', 'Accept'), ('minor_revision', 'Minor Revision'), ('major_revision', 'Major Revision'), ('reject', 'Reject')], max_length=32),
        ),
    ]
