# Generated by Django 6.0.7 on 2026-08-04 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_sponsor_options_sponsor_display_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(default='reviewer_editor', max_length=50)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='article',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='academic_position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified_researcher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='publications_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='research_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='research_field',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
