# Generated by Django 6.0.7 on 2026-08-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_reviewerinvitation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
    ]
