from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("journal", "0008_user_account_status")]

    operations = [
        migrations.AddField("user", "discipline", models.CharField(blank=True, choices=[("medicine", "Medicine"), ("pharmacy", "Pharmacy"), ("dentistry", "Dentistry / Dental Surgery"), ("nursing", "Nursing"), ("public_health", "Public Health"), ("clinical_psychology", "Clinical Psychology"), ("biomedical_sciences", "Biomedical Sciences"), ("health_informatics", "Health Informatics"), ("health_communication", "Health Communication & Journalism"), ("other", "Other Health Discipline")], max_length=40)),
        migrations.AddField("user", "academic_stage", models.CharField(blank=True, choices=[("undergraduate", "Undergraduate"), ("postgraduate", "Postgraduate"), ("early_career", "Early-career researcher"), ("faculty", "Faculty / Supervisor"), ("professional", "Health professional")], max_length=30)),
        migrations.AddField("article", "article_type", models.CharField(choices=[("original_research", "Original Research"), ("review", "Review Article"), ("case_report", "Case Report / Case Series"), ("short_communication", "Short Communication"), ("health_communication", "Health Communication / Journalism"), ("commentary", "Commentary / Opinion"), ("student_research_note", "Student Research Note")], default="original_research", max_length=40)),
        migrations.AddField("article", "discipline", models.CharField(choices=[("medicine", "Medicine"), ("pharmacy", "Pharmacy"), ("dentistry", "Dentistry / Dental Surgery"), ("nursing", "Nursing"), ("public_health", "Public Health"), ("clinical_psychology", "Clinical Psychology"), ("biomedical_sciences", "Biomedical Sciences"), ("health_informatics", "Health Informatics"), ("health_communication", "Health Communication & Journalism"), ("interdisciplinary", "Interdisciplinary Health Research"), ("other", "Other Health Discipline")], default="medicine", max_length=40)),
        migrations.AddField("article", "research_question", models.TextField(blank=True)),
        migrations.AddField("article", "supervisor_name", models.CharField(blank=True, max_length=255)),
        migrations.AddField("article", "student_initiated", models.BooleanField(default=True)),
        migrations.AddField("article", "slug", models.SlugField(blank=True, max_length=300, null=True, unique=True)),
        migrations.AddField("article", "license", models.CharField(blank=True, default="CC BY-NC 4.0", max_length=255)),
        migrations.AddField("article", "funding_statement", models.TextField(blank=True)),
        migrations.AddField("article", "conflict_of_interest", models.TextField(blank=True)),
        migrations.AddField("article", "ethics_statement", models.TextField(blank=True)),
        migrations.AddField("article", "data_availability", models.TextField(blank=True)),
        migrations.AddField("article", "ai_use_statement", models.TextField(blank=True)),
        migrations.AddField("article", "received_date", models.DateField(blank=True, null=True)),
        migrations.AddField("article", "accepted_date", models.DateField(blank=True, null=True)),
        migrations.AddField("article", "volume", models.PositiveIntegerField(blank=True, null=True)),
        migrations.AddField("article", "issue", models.PositiveIntegerField(blank=True, null=True)),
        migrations.AddField("article", "pages", models.CharField(blank=True, max_length=50)),
        migrations.AddField("article", "citation_text", models.TextField(blank=True)),
        migrations.AddField("article", "submitted_at", models.DateTimeField(blank=True, null=True)),
        migrations.AddField("article", "last_reviewed_at", models.DateTimeField(blank=True, null=True)),
        migrations.AddField("article", "revision_round", models.PositiveIntegerField(default=0)),
        migrations.AddField("article", "editorial_notes", models.TextField(blank=True)),
        migrations.AddField("review", "comments_to_author", models.TextField(blank=True)),
        migrations.AddField("review", "confidential_comments", models.TextField(blank=True)),
        migrations.AddField("review", "methods_rating", models.PositiveIntegerField(default=0)),
        migrations.AddField("review", "clarity_rating", models.PositiveIntegerField(default=0)),
        migrations.AddField("review", "ethics_rating", models.PositiveIntegerField(default=0)),
        migrations.AddField("review", "conflict_of_interest", models.BooleanField(default=False)),
        migrations.AddField("review", "ai_assistance_used", models.BooleanField(default=False)),
        migrations.AddField("reviewassignment", "deadline", models.DateTimeField(blank=True, null=True)),
        migrations.AddField("reviewassignment", "accepted_at", models.DateTimeField(blank=True, null=True)),
        migrations.AddField("reviewassignment", "completed_at", models.DateTimeField(blank=True, null=True)),
        migrations.AlterField("article", "status", models.CharField(choices=[("draft", "Draft"), ("submitted", "Submitted"), ("under_review", "Under Review"), ("revision", "Revision Required"), ("accepted", "Accepted"), ("editor_decision", "Editorial Decision"), ("rejected", "Rejected"), ("published", "Published")], default="draft", max_length=20)),
        migrations.CreateModel(name="ArticleRevision", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("round", models.PositiveIntegerField(default=1)),
            ("manuscript_file", models.FileField(blank=True, null=True, upload_to="articles/revisions/")),
            ("response_to_reviewers", models.TextField(blank=True)),
            ("author_notes", models.TextField(blank=True)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="journal.article")),
            ("submitted_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="submitted_revisions", to="journal.user")),
        ], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="EditorialDecision", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("decision", models.CharField(choices=[("accept", "Accept"), ("minor_revision", "Minor Revision"), ("major_revision", "Major Revision"), ("reject", "Reject")], max_length=32)),
            ("rationale", models.TextField(blank=True)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="editorial_decisions", to="journal.article")),
            ("editor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="editorial_decisions", to="journal.user")),
        ], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="AIUsageLog", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("task", models.CharField(choices=[("research", "Research assistance"), ("writing", "Scientific writing support"), ("grammar", "Language support"), ("keywords", "Keyword assistance"), ("summarize", "Summary"), ("plain_language", "Plain-language summary"), ("integrity_check", "Integrity / completeness check"), ("reviewer_support", "Reviewer support"), ("chat", "Research chat")], max_length=40)),
            ("provider", models.CharField(default="mock", max_length=80)),
            ("model", models.CharField(blank=True, max_length=120)),
            ("input_characters", models.PositiveIntegerField(default=0)),
            ("output_characters", models.PositiveIntegerField(default=0)),
            ("disclosed", models.BooleanField(default=False)),
            ("success", models.BooleanField(default=True)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("article", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ai_usage", to="journal.article")),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ai_usage", to="journal.user")),
        ], options={"ordering": ["-created_at"]}),
    ]
