# Generated by Django 6.0.8 on 2026-08-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0022_remove_journal_support_gift_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchidea',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='researchopportunity',
            options={'ordering': ['deadline', '-created_at']},
        ),
        migrations.RenameIndex(
            model_name='passportevidence',
            new_name='journal_pas_user_id_59ff41_idx',
            old_name='journal_pas_user_id_eviden_5e8291_idx',
        ),
        migrations.RenameIndex(
            model_name='studentgift',
            new_name='journal_stu_recipie_e34228_idx',
            old_name='journal_stud_recipient_3e1c6e_idx',
        ),
        migrations.RenameIndex(
            model_name='studentgift',
            new_name='journal_stu_gift_co_1d38ee_idx',
            old_name='journal_stud_gift_co_5b6f5e_idx',
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reviewerinvitation',
            name='role',
            field=models.CharField(default='reviewer', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='academic_stage',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='discipline',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
