# Generated by Django 6.0.7 on 2026-08-24 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0023_alter_researchidea_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='research_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuscripts', to='journal.researchproject'),
        ),
    ]
