import { useRouter } from 'next/router'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import ApplicationShell from '../../../components/ApplicationShell'
import api from '../../../utils/api'

export default function ModulePage(){
  const router=useRouter(); const [data,setData]=useState<any>(null); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [answers,setAnswers]=useState<Record<string,string[]>>({}); const id=router.query.id
  useEffect(()=>{if(id) api.get(`/academy/modules/${id}/`).then(r=>setData(r.data)).catch(e=>setError(e?.response?.data?.detail||'This module is locked.'))},[id])
  const complete=async(lesson:number)=>{try{await api.post(`/academy/lessons/${lesson}/complete/`);setMessage('✓ Progress saved.')}catch(e:any){setMessage(e?.response?.data?.detail||'Could not save progress.')}}
  const submit=async()=>{try{const r=await api.post(`/academy/quizzes/${data.quiz.id}/submit/`,{answers});setMessage(r.data.passed?`✓ ${r.data.score}% — assessment passed.`:`${r.data.score}% — review and try again.`)}catch(e:any){setMessage(e?.response?.data?.detail||'Could not submit assessment.')}}
  const shell=(children:any)=><ApplicationShell name="Research Academy" description="Learning module" nav={[["/research-academy","Academy Home"],["/research-academy/dashboard","My Learning"],["/research-academy/certificates","Certificates"]]}>{children}</ApplicationShell>
  if(error)return shell(<main className="mx-auto max-w-4xl px-6 py-16"><div className="rounded-3xl border border-rose-200 bg-rose-50 p-8"><h1 className="text-3xl font-black">Learning locked</h1><p className="mt-3 text-rose-900">{error}</p><Link href="/research-academy" className="mt-6 inline-flex rounded-xl bg-slate-950 px-5 py-3 font-black text-white">Back to Academy</Link></div></main>)
  if(!data)return shell(<main className="mx-auto max-w-4xl px-6 py-16"><div className="rounded-3xl bg-white p-8 shadow-sm">Loading module…</div></main>)
  return shell(<main className="mx-auto max-w-5xl px-6 pb-16"><div className="rounded-3xl bg-slate-950 p-8 text-white"><div className="text-xs font-black uppercase tracking-[0.2em] text-emerald-300">{data.pathway_name||`Level ${data.level}`}</div><h1 className="mt-3 text-4xl font-black">{data.title}</h1><p className="mt-4 max-w-3xl text-slate-300">{data.summary}</p></div><section className="mt-6 rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200"><h2 className="text-2xl font-black">Learning objectives</h2><ul className="mt-4 grid gap-3 md:grid-cols-2">{(data.objectives||[]).map((x:string)=><li key={x} className="rounded-2xl bg-slate-50 p-4 text-sm font-semibold">✓ {x}</li>)}</ul></section>{(data.lessons||[]).map((lesson:any)=><article key={lesson.id} className="mt-5 rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200"><div className="text-xs font-black uppercase tracking-[0.16em] text-emerald-700">Lesson {lesson.order}</div><h2 className="mt-2 text-2xl font-black">{lesson.title}</h2><div className="mt-5 whitespace-pre-line leading-8 text-slate-700">{lesson.body}</div>{lesson.video_url&&<a href={lesson.video_url} target="_blank" rel="noreferrer" className="mt-5 inline-flex rounded-xl bg-slate-950 px-4 py-2.5 font-black text-white">Open video ↗</a>}<button onClick={()=>complete(lesson.id)} className="mt-6 rounded-xl bg-emerald-600 px-5 py-3 font-black text-white">Mark lesson complete ✓</button></article>)}{data.quiz&&<section className="mt-6 rounded-3xl bg-white p-7 shadow-sm ring-1 ring-violet-100"><div className="text-xs font-black uppercase tracking-[0.16em] text-violet-700">Assessment · Pass {data.quiz.pass_mark}%</div><h2 className="mt-2 text-3xl font-black">{data.quiz.title}</h2><div className="mt-6 space-y-5">{data.quiz.questions.map((q:any)=><div key={q.id} className="rounded-2xl border border-slate-200 p-5"><div className="font-black">{q.order}. {q.prompt}</div><div className="mt-4 grid gap-2">{q.choices.map((c:any)=><label key={c.id} className="flex items-center gap-3 rounded-xl border p-3"><input type="radio" name={`q-${q.id}`} onChange={()=>setAnswers({...answers,[q.id]:[String(c.id)]})}/><span>{c.text}</span></label>)}</div></div>)}</div><button onClick={submit} className="mt-7 rounded-xl bg-violet-700 px-5 py-3 font-black text-white">Submit assessment</button></section>}{message&&<div className="sticky bottom-4 mt-6 rounded-2xl bg-slate-950 p-4 text-center font-bold text-white">{message}</div>}</main>)
}
