from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[('rsre_core','0001_initial')]
    operations=[
        migrations.AddField(model_name='platformsetting',name='whatsapp_phone_number_id',field=models.CharField(blank=True,max_length=120)),
        migrations.AddField(model_name='platformsetting',name='whatsapp_business_account_id',field=models.CharField(blank=True,max_length=120)),
        migrations.AddField(model_name='platformsetting',name='whatsapp_api_version',field=models.CharField(blank=True,default='v23.0',max_length=30)),
        migrations.AddField(model_name='platformsetting',name='whatsapp_group_create_url',field=models.URLField(blank=True)),
        migrations.AddField(model_name='notificationoutbox',name='event_key',field=models.CharField(blank=True,max_length=120)),
        migrations.AddField(model_name='notificationoutbox',name='metadata',field=models.JSONField(blank=True,default=dict)),
        migrations.CreateModel(name='FeatureComponent',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('key',models.SlugField(max_length=100)),('title',models.CharField(max_length=180)),('description',models.TextField(blank=True)),('component_type',models.CharField(choices=[('section','Section'),('card','Card'),('tool','Tool'),('widget','Widget'),('navigation','Navigation'),('cta','Call to action')],default='section',max_length=30)),('route',models.CharField(blank=True,max_length=180)),('enabled',models.BooleanField(default=True)),('order',models.PositiveIntegerField(default=0)),('config_json',models.JSONField(blank=True,default=dict)),('updated_at',models.DateTimeField(auto_now=True)),('application',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='feature_components',to='rsre_core.application'))],options={'ordering':['order','title']}),
        migrations.AddConstraint(model_name='featurecomponent',constraint=models.UniqueConstraint(fields=('application','key'),name='rsre_unique_feature_component')),
        migrations.CreateModel(name='WhatsAppCommunity',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=180)),('description',models.TextField(blank=True)),('purpose',models.CharField(default='learning',max_length=120)),('invite_url',models.URLField(blank=True)),('provider_group_id',models.CharField(blank=True,max_length=180)),('active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('application',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='whatsapp_communities',to='rsre_core.application')),('owner',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='owned_whatsapp_communities',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='WhatsAppCommunityMember',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('status',models.CharField(choices=[('invited','Invited'),('joined','Joined'),('left','Left'),('removed','Removed')],default='invited',max_length=20)),('joined_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('community',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='members',to='rsre_core.whatsappcommunity')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='whatsapp_community_memberships',to=settings.AUTH_USER_MODEL))]),
        migrations.AddConstraint(model_name='whatsappcommunitymember',constraint=models.UniqueConstraint(fields=('community','user'),name='rsre_unique_whatsapp_membership')),
        migrations.CreateModel(name='WhatsAppCommunityMessage',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('message',models.TextField()),('status',models.CharField(default='queued',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('community',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='messages',to='rsre_core.whatsappcommunity')),('sender',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))]),
    ]
