# Generated by Django 6.0.8 on 2026-08-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsre_core', '0004_collaboration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappcommunity',
            options={'ordering': ['-created_at']},
        ),
    ]
