import React, {useEffect, useState} from 'react'
import {useRouter} from 'next/router'
import Link from 'next/link'
import ApplicationShell from '../../components/ApplicationShell'
import api from '../../utils/api'

export default function SandboxWorkbench(){
  const router=useRouter(); const {id}=router.query
  const [w,setW]=useState<any>(null); const [noteTitle,setNoteTitle]=useState(''); const [noteBody,setNoteBody]=useState(''); const [datasetName,setDatasetName]=useState(''); const [datasetType,setDatasetType]=useState('synthetic'); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
  const load=async()=>{if(!id)return; try{const r=await api.get(`/research-sandbox/${id}/`);setW(r.data)}catch(e:any){setError(e?.response?.data?.detail||'Unable to load workspace.')}}
  useEffect(()=>{load()},[id])
  const addNote=async()=>{if(!noteTitle.trim())return;setBusy(true);try{await api.post(`/research-sandbox/${id}/add-note/`,{title:noteTitle,body:noteBody,note_type:'research_note'});setNoteTitle('');setNoteBody('');load()}catch(e:any){setError('Could not save note.')}finally{setBusy(false)}}
  const addDataset=async()=>{if(!datasetName.trim())return;setBusy(true);try{await api.post(`/research-sandbox/${id}/add-dataset/`,{name:datasetName,data_type:datasetType,description:'',source:'',authorization_reference:'',safety_status:'review',contains_direct_identifiers:false});setDatasetName('');load()}catch(e:any){setError('Could not add dataset.')}finally{setBusy(false)}}
  if(!w)return <ApplicationShell name="Sandbox workbench" description="Research experimentation workspace" nav={[["/research-sandbox","Sandbox"]]}><main className="mx-auto max-w-6xl px-6 py-12"><div className="rounded-3xl border border-slate-200 bg-white p-8">{error||'Loading workbench…'}</div></main></ApplicationShell>
  return <ApplicationShell name={w.title} description="Private research workbench" nav={[["/research-sandbox","All workspaces"],[`/research-sandbox/${id}`,'Workbench']] }><main className="mx-auto max-w-6xl px-6 pb-16 pt-6">
    <div className="mb-5 text-sm font-bold"><Link href="/research-sandbox" className="text-cyan-700">← Research Sandbox</Link></div>
    {error&&<div className="mb-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{error}</div>}
    <section className="rounded-3xl border border-slate-200 bg-slate-950 p-8 text-white"><div className="text-xs font-black uppercase tracking-[0.2em] text-cyan-300">Sandbox workbench</div><div className="mt-2 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-4xl font-black">{w.title}</h1><p className="mt-3 max-w-3xl leading-7 text-slate-300">{w.description || 'Use this space to test ideas, record decisions and make your analysis reproducible.'}</p></div><div className="rounded-2xl bg-white/10 px-4 py-3 text-sm font-bold">{w.status}</div></div><div className="mt-6 grid gap-3 sm:grid-cols-4">{[['Notes',w.notes?.length||0],['Datasets',w.datasets?.length||0],['Topic',w.research_topic||'—'],['Mode',w.visibility||'private']].map(([a,b])=><div key={a} className="rounded-2xl bg-white/10 p-4"><div className="text-xs font-bold text-slate-400">{a}</div><div className="mt-1 font-black">{b}</div></div>)}</div></section>
    <div className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-3xl border border-slate-200 bg-white p-7"><div className="flex items-end justify-between"><div><div className="text-xs font-black uppercase tracking-[0.18em] text-cyan-700">Notebook</div><h2 className="mt-1 text-2xl font-black">Research notes</h2></div><div className="text-xs font-bold text-slate-500">Document decisions, not just conclusions.</div></div><div className="mt-5 space-y-3">{(w.notes||[]).map((n:any)=><div key={n.id} className="rounded-2xl border border-slate-200 p-4"><div className="font-black">{n.title}</div><div className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{n.body||'No note content.'}</div></div>)}{!(w.notes||[]).length&&<div className="rounded-2xl border border-dashed border-slate-300 p-6 text-sm text-slate-500">No notes yet.</div>}</div><div className="mt-6 border-t border-slate-100 pt-6"><h3 className="font-black">Add a note</h3><input className="mt-3 w-full rounded-xl border border-slate-300 px-4 py-3" placeholder="Note title" value={noteTitle} onChange={e=>setNoteTitle(e.target.value)}/><textarea className="mt-3 w-full rounded-xl border border-slate-300 px-4 py-3" rows={5} placeholder="Observation, method decision, assumption, result or next test…" value={noteBody} onChange={e=>setNoteBody(e.target.value)}/><button disabled={busy} onClick={addNote} className="mt-3 rounded-xl bg-slate-950 px-4 py-2 text-sm font-black text-white">Save note</button></div></section>
    <section className="rounded-3xl border border-slate-200 bg-white p-7"><div className="text-xs font-black uppercase tracking-[0.18em] text-cyan-700">Data room</div><h2 className="mt-1 text-2xl font-black">Datasets</h2><p className="mt-2 text-sm leading-6 text-slate-600">Only use data you are authorized to use. New datasets stay in review until their safety status is established.</p><div className="mt-5 space-y-3">{(w.datasets||[]).map((d:any)=><div key={d.id} className="rounded-2xl border border-slate-200 p-4"><div className="font-black">{d.name}</div><div className="mt-2 flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-slate-100 px-3 py-1">{d.data_type}</span><span className="rounded-full bg-amber-50 px-3 py-1 text-amber-800">{d.safety_status}</span>{d.contains_direct_identifiers&&<span className="rounded-full bg-red-50 px-3 py-1 text-red-800">Direct identifiers</span>}</div></div>)}{!(w.datasets||[]).length&&<div className="rounded-2xl border border-dashed border-slate-300 p-6 text-sm text-slate-500">No datasets added.</div>}</div><div className="mt-6 border-t border-slate-100 pt-6"><h3 className="font-black">Add dataset record</h3><input className="mt-3 w-full rounded-xl border border-slate-300 px-4 py-3" placeholder="Dataset name" value={datasetName} onChange={e=>setDatasetName(e.target.value)}/><select className="mt-3 w-full rounded-xl border border-slate-300 px-4 py-3" value={datasetType} onChange={e=>setDatasetType(e.target.value)}><option value="synthetic">Synthetic</option><option value="public">Public</option><option value="authorized">Authorized research data</option></select><button disabled={busy} onClick={addDataset} className="mt-3 rounded-xl bg-cyan-700 px-4 py-2 text-sm font-black text-white">Add dataset</button></div></section></div>
    <section className="mt-6 rounded-3xl border border-cyan-200 bg-cyan-50 p-6"><div className="font-black text-slate-950">Ready to become a real study?</div><p className="mt-1 text-sm leading-6 text-slate-700">When the research question and methods are mature, move the idea into the Incubator for team, mentor, ethics and milestone management.</p><Link href="/research-incubator" className="mt-3 inline-flex rounded-xl bg-slate-950 px-4 py-2 text-sm font-black text-white">Open Incubator →</Link></section>
  </main></ApplicationShell>
}
