from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[('academy','0005_alter_module_slug'),('rsre_core','0002_rsre_features_whatsapp')]
    operations=[
        migrations.CreateModel(name='LessonResource',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=255)),('resource_type',models.CharField(choices=[('reading','Reading'),('video','Video'),('tool','Tool'),('guideline','Guideline'),('template','Template'),('dataset','Dataset')],default='reading',max_length=30)),('url',models.URLField(blank=True)),('description',models.TextField(blank=True)),('source',models.CharField(blank=True,max_length=255)),('required',models.BooleanField(default=False)),('order',models.PositiveIntegerField(default=0)),('active',models.BooleanField(default=True)),('lesson',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='resources',to='academy.lesson'))],options={'ordering':['order','title']}),
        migrations.CreateModel(name='CourseCohort',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=180)),('code',models.SlugField(max_length=120,unique=True)),('description',models.TextField(blank=True)),('starts_at',models.DateTimeField(blank=True,null=True)),('ends_at',models.DateTimeField(blank=True,null=True)),('capacity',models.PositiveIntegerField(default=50)),('active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('level',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='cohorts',to='academy.level')),('pathway',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='cohorts',to='academy.specialistpathway')),('whatsapp_community',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='academy_cohorts',to='rsre_core.whatsappcommunity'))]),
        migrations.CreateModel(name='CourseCohortMember',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('joined_at',models.DateTimeField(auto_now_add=True)),('status',models.CharField(default='active',max_length=20)),('cohort',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='members',to='academy.coursecohort')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='academy_cohort_memberships',to=settings.AUTH_USER_MODEL))]),
        migrations.AddConstraint(model_name='coursecohortmember',constraint=models.UniqueConstraint(fields=('cohort','user'),name='academy_unique_cohort_member')),
    ]
