import {useEffect,useMemo,useState} from 'react';
import ApplicationShell from '../components/ApplicationShell';

const API=process.env.NEXT_PUBLIC_API_URL||process.env.NEXT_PUBLIC_API_BASE||'/api/rsre';
function auth(): Record<string, string> {
  if (typeof window === 'undefined') return {}
  const t = localStorage.getItem('access') || localStorage.getItem('token')
  return t ? { Authorization: 'Bearer ' + t } : {}
}
const purposes=[['research_project','Project collaborator'],['mentorship','Mentor / mentee'],['coauthor','Co-author'],['methods','Methods / statistics'],['peer_learning','Peer learning']];

export default function Collaboration(){
 const [data,setData]=useState({people:[],incoming:[],outgoing:[]}); const [q,setQ]=useState(''); const [purpose,setPurpose]=useState('research_project'); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<number|null>(null); const [message,setMessage]=useState(''); const [selected,setSelected]=useState<any|null>(null);
 async function load(term=''){setLoading(true); try{const r=await fetch(`${API}/collaboration/?q=${encodeURIComponent(term)}`,{headers:{...auth()}}); const j=await r.json(); setData({people:j.people||[],incoming:j.incoming||[],outgoing:j.outgoing||[]});} finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function request(id:number){setBusy(id); setMessage(''); try{const r=await fetch(`${API}/collaboration/`,{method:'POST',headers:{'Content-Type':'application/json',...auth()},body:JSON.stringify({recipient:id,purpose,message:`I would like to connect for ${purposes.find(([v])=>v===purpose)?.[1].toLowerCase()||'research collaboration'} through RSRE.`})}); const j=await r.json(); if(!r.ok) throw new Error(j.detail||'Unable to send request'); setMessage('Request sent.'); setSelected(null); load(q);}catch(e:any){setMessage(e.message)}finally{setBusy(null)}}
 async function action(id:number,action:string){await fetch(`${API}/collaboration/requests/${id}/`,{method:'POST',headers:{'Content-Type':'application/json',...auth()},body:JSON.stringify({action})}); load(q)}
 const connectedCount=data.people.filter((p:any)=>p.connected).length;
 return <ApplicationShell name="Collaboration Network" description="Find the right people for a specific research need." nav={[["/collaboration","Network"],["/research-incubator","Projects"],["/research-passport","Profiles"]]}>
  <main className="mx-auto max-w-7xl px-4 pb-16 sm:px-6">
   <section className="overflow-hidden rounded-[2rem] bg-slate-950 text-white shadow-sm">
    <div className="grid gap-8 px-6 py-8 md:grid-cols-[1.2fr,.8fr] md:px-9 md:py-10">
     <div><div className="text-xs font-black uppercase tracking-[.2em] text-violet-300">Research matching</div><h2 className="mt-3 text-4xl font-black tracking-tight md:text-5xl">Find the person your research question is missing.</h2><p className="mt-4 max-w-2xl text-base leading-7 text-slate-300">Search by field, institution, methods or interests. RSRE is for purposeful research connections—not a social-media feed.</p>
      <div className="mt-6 grid gap-3 sm:grid-cols-[1fr_auto]"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load(q)} placeholder="e.g. malaria • biostatistics • Kigali • R" className="rounded-2xl border border-white/10 bg-white/10 px-4 py-3 text-white placeholder:text-slate-400 outline-none"/><button onClick={()=>load(q)} className="rounded-2xl bg-white px-5 py-3 font-black text-slate-950">Find people</button></div>
      {message&&<p className="mt-4 text-sm font-bold text-emerald-300">{message}</p>}
     </div>
     <div className="rounded-3xl border border-white/10 bg-white/5 p-6"><div className="text-xs font-black uppercase tracking-wider text-slate-400">How it works</div><div className="mt-4 space-y-4">{[['01','Search','Find people by research-relevant signals.'],['02','Understand fit','Review interests, methods and research stage.'],['03','Connect with purpose','Start a focused request; project work stays in the Incubator.']].map(([n,t,d])=><div key={n} className="flex gap-4"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-white/10 text-xs font-black">{n}</div><div><div className="font-black">{t}</div><div className="mt-1 text-sm leading-6 text-slate-400">{d}</div></div></div>)}</div></div>
    </div>
   </section>

   {data.incoming.length>0&&<section className="mt-8 rounded-3xl bg-white p-6 ring-1 ring-slate-200"><div className="flex items-center justify-between"><div><h3 className="text-xl font-black">Requests waiting for you</h3><p className="text-sm text-slate-500">Review why someone wants to collaborate before accepting.</p></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-black text-amber-800">{data.incoming.length} pending</span></div><div className="mt-5 grid gap-3 md:grid-cols-2">{data.incoming.map((r:any)=><div key={r.id} className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><div className="font-black">{r.requester_name}</div><div className="mt-1 text-sm text-slate-500">{purposes.find(([v])=>v===r.purpose)?.[1]||r.purpose}{r.desired_role?` • ${r.desired_role}`:''}</div>{r.message&&<p className="mt-2 text-sm leading-6 text-slate-600">{r.message}</p>}<div className="mt-4 flex gap-2"><button onClick={()=>action(r.id,'accept')} className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-black text-white">Accept</button><button onClick={()=>action(r.id,'decline')} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-black">Decline</button></div></div>)}</div></section>}

   <section className="mt-8 grid gap-4 md:grid-cols-3"><div className="rounded-3xl border border-violet-200 bg-violet-50/70 p-6"><div className="text-xs font-black uppercase tracking-[0.18em] text-violet-700">Mentorship</div><h3 className="mt-2 text-xl font-black">Find guidance for the next decision.</h3><p className="mt-2 text-sm leading-6 text-slate-600">Ask for a focused methods, career or project connection.</p></div><div className="rounded-3xl border border-blue-200 bg-blue-50/70 p-6"><div className="text-xs font-black uppercase tracking-[0.18em] text-blue-700">Co-authoring</div><h3 className="mt-2 text-xl font-black">Build the right team.</h3><p className="mt-2 text-sm leading-6 text-slate-600">Connect around a defined research purpose, then execute inside the Incubator.</p></div><div className="rounded-3xl border border-emerald-200 bg-emerald-50/70 p-6"><div className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">Methods fit</div><h3 className="mt-2 text-xl font-black">Match skills, not popularity.</h3><p className="mt-2 text-sm leading-6 text-slate-600">Search by field, institution, methods and research stage.</p></div></section>

   <section className="mt-8"><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><div className="text-xs font-black uppercase tracking-[.18em] text-violet-700">Network</div><h3 className="mt-1 text-3xl font-black">Researchers who may fit</h3><p className="mt-1 text-sm text-slate-500">{loading?'Searching…':`${data.people.length} matches${connectedCount?` • ${connectedCount} connected`:''}`}</p></div><div className="flex items-center gap-2 rounded-2xl border border-slate-200 bg-white p-1"><span className="px-3 py-2 text-xs font-black text-slate-500">Connect for</span><select value={purpose} onChange={e=>setPurpose(e.target.value)} className="rounded-xl bg-slate-50 px-3 py-2 text-xs font-black text-slate-800">{purposes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div></div>
    <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{data.people.map((p:any)=><article key={p.id} className="group rounded-3xl bg-white p-6 ring-1 ring-slate-200 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-violet-50 text-lg font-black text-violet-800">{(p.name||'?').split(' ').map((x:string)=>x[0]).slice(0,2).join('')}</div><div className="min-w-0"><div className="flex items-center gap-2"><h4 className="truncate text-lg font-black">{p.name}</h4>{p.verified&&<span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-black text-emerald-700">Verified</span>}</div><p className="mt-1 text-sm text-slate-500">{p.institution||'RSRE researcher'}</p></div></div><div className="mt-4 flex flex-wrap gap-2">{p.discipline&&<span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{p.discipline}</span>}{p.academic_stage&&<span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{p.academic_stage}</span>}{p.research_field&&<span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{p.research_field}</span>}</div>{p.research_interests?.length>0&&<div className="mt-4"><div className="text-[11px] font-black uppercase tracking-wider text-slate-400">Research interests</div><p className="mt-2 text-sm leading-6 text-slate-600">{p.research_interests.slice(0,5).join(' • ')}</p></div>}{p.biography&&<p className="mt-3 line-clamp-2 text-sm leading-6 text-slate-500">{p.biography}</p>}<div className="mt-5 flex gap-2">{p.connected?<span className="flex-1 rounded-xl bg-emerald-50 px-4 py-3 text-center text-sm font-black text-emerald-700">Connected</span>:p.request_pending?<span className="flex-1 rounded-xl bg-slate-100 px-4 py-3 text-center text-sm font-black text-slate-600">Request pending</span>:<><button onClick={()=>setSelected(p)} className="flex-1 rounded-xl border border-slate-200 px-4 py-3 text-sm font-black">View fit</button><button disabled={busy===p.id} onClick={()=>request(p.id)} className="flex-1 rounded-xl bg-violet-700 px-4 py-3 text-sm font-black text-white">{busy===p.id?'Sending…':'Connect'}</button></>}</div></article>)}</div>
   </section>
  </main>
  {selected&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/50 p-4 sm:items-center"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-wider text-violet-700">Research fit</div><h3 className="mt-1 text-2xl font-black">{selected.name}</h3><p className="text-sm text-slate-500">{selected.institution||'RSRE researcher'}</p></div><button onClick={()=>setSelected(null)} className="rounded-xl border px-3 py-2 text-sm font-black">Close</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-[11px] font-black uppercase tracking-wider text-slate-400">Field</div><div className="mt-1 font-black">{selected.research_field||'Not specified'}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-[11px] font-black uppercase tracking-wider text-slate-400">Stage</div><div className="mt-1 font-black">{selected.academic_stage||'Not specified'}</div></div></div>{selected.research_interests?.length>0&&<div className="mt-5"><div className="text-[11px] font-black uppercase tracking-wider text-slate-400">Interests</div><p className="mt-2 text-sm leading-6 text-slate-600">{selected.research_interests.join(' • ')}</p></div>}<div className="mt-6 flex gap-2"><button onClick={()=>setSelected(null)} className="flex-1 rounded-xl border border-slate-200 px-4 py-3 text-sm font-black">Back</button><button onClick={()=>request(selected.id)} className="flex-1 rounded-xl bg-violet-700 px-4 py-3 text-sm font-black text-white">Connect for {purposes.find(([v])=>v===purpose)?.[1].toLowerCase()}</button></div></div></div>}
 </ApplicationShell>
}
