import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import Layout from "../components/Layout";
import api from "../utils/api";

export default function Archive(){
  const [articles,setArticles]=useState<any[]>([]); const [loading,setLoading]=useState(true);
  useEffect(()=>{api.get("/articles/?status=published&is_published=true").then(r=>setArticles(r.data?.results||r.data||[])).catch(()=>setArticles([])).finally(()=>setLoading(false));},[]);
  const groups=useMemo(()=>{const map:Record<string,any[]>= {}; for(const a of articles){const year=String(a.year||(a.published_date?new Date(a.published_date).getFullYear():"Unknown")); (map[year] ||= []).push(a);} return Object.entries(map).sort((a,b)=>Number(b[0])-Number(a[0]));},[articles]);
  return <Layout><main className="min-h-screen bg-slate-50"><section className="bg-slate-950 text-white py-16"><div className="rsjh-page"><p className="rsjh-eyebrow text-emerald-300">JOURNAL ARCHIVE</p><h1 className="rsjh-title mt-3">Published research, organised for the long term.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">Browse the permanent RSJH record by year, volume and issue as the journal grows.</p></div></section><section className="rsjh-section"><div className="rsjh-page"><div className="mb-8 rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-sm text-emerald-900"><strong>Open and free by design.</strong> RSJH publication is free for students and researchers. Browse the permanent scientific record below.</div>{loading?<div className="rsjh-card p-8">Loading archive...</div>:groups.length===0?<div className="rsjh-card p-10 text-center text-slate-500">No published articles yet.</div>:groups.map(([year,items])=><section key={year} className="mb-12"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="rsjh-eyebrow text-emerald-700">PUBLICATIONS</p><h2 className="mt-1 text-4xl font-black text-slate-950">{year}</h2></div><span className="rsjh-chip">{items.length} article{items.length===1?"":"s"}</span></div><div className="mt-5 grid gap-5 lg:grid-cols-2">{items.map(a=><Link key={a.id} href={`/articles/${a.id}`} className="rsjh-card rsjh-card-hover p-6"><div className="flex flex-wrap items-center gap-2"><span className="rsjh-chip">{a.volume?`Vol. ${a.volume}`:"Volume pending"}</span>{a.issue&&<span className="rsjh-chip">Issue {a.issue}</span>}<span className="rsjh-chip">{a.article_type?.replace(/_/g," ")||"Article"}</span></div><h3 className="mt-4 text-xl font-black">{a.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{a.abstract||"Published RSJH article."}</p><div className="mt-5 text-sm font-bold text-emerald-700">View permanent article record →</div></Link>)}</div></section>)}</div></section></main></Layout>
}
