import Link from 'next/link';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/router';
import ApplicationShell from '../../components/ApplicationShell';
import api from '../../api';

const STATUS_LABELS:any={developing:'Developing',protocol:'Protocol',ethics:'Ethics & governance',data_collection:'Data collection',analysis:'Analysis',manuscript:'Manuscript',publication:'Publication',completed:'Completed',paused:'Paused'};
const STATUS_ORDER=['developing','protocol','ethics','data_collection','analysis','manuscript','publication','completed'];

export default function ProjectCockpit(){
 const router=useRouter(); const [project,setProject]=useState<any>(null); const [loading,setLoading]=useState(true); const [message,setMessage]=useState(''); const [milestone,setMilestone]=useState({title:'',description:'',due_date:''}); const [saving,setSaving]=useState(false);
 const id=router.query.id;
 async function load(){if(!id)return;setLoading(true);try{const r=await api.get(`/research-projects/${id}/`);setProject(r.data)}catch(e:any){setMessage(e?.response?.data?.detail||'Could not load this project.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[id]);
 async function advance(status:string){try{await api.post(`/research-projects/${id}/advance/`,{status});await load();setMessage(`Project stage updated to ${STATUS_LABELS[status]||status}.`)}catch(e:any){setMessage(e?.response?.data?.detail||'Could not update the project stage.')}}
 async function addMilestone(e:FormEvent){e.preventDefault();setSaving(true);try{await api.post(`/research-projects/${id}/add-milestone/`,{...milestone,order:(project?.milestones?.length||0)+1,status:'todo'});setMilestone({title:'',description:'',due_date:''});await load();setMessage('Milestone added.')}catch(e:any){setMessage(e?.response?.data?.detail||'Could not add milestone.')}finally{setSaving(false)}}
 const currentIndex=Math.max(0,STATUS_ORDER.indexOf(project?.status)); const nextStatus=STATUS_ORDER[currentIndex+1]; const done=(project?.milestones||[]).filter((m:any)=>m.status==='done').length;
 if(loading)return <ApplicationShell name="Research Incubator" description="Project cockpit"><main className="mx-auto max-w-6xl px-6 py-16"><div className="rounded-3xl bg-white p-8 text-slate-500">Loading project…</div></main></ApplicationShell>;
 if(!project)return <ApplicationShell name="Research Incubator" description="Project cockpit"><main className="mx-auto max-w-6xl px-6 py-16"><div className="rounded-3xl border bg-white p-8"><h1 className="text-2xl font-black">Project not found</h1><Link href="/research-incubator" className="mt-4 inline-block font-bold text-emerald-700">← Back to Incubator</Link></div></main></ApplicationShell>;
 return <ApplicationShell name="Research Incubator" description="Project cockpit"><main className="mx-auto max-w-7xl px-6 pb-16">
  <div className="mb-6 text-sm font-bold text-slate-500"><Link href="/research-incubator" className="hover:text-slate-950">Incubator</Link> <span className="mx-2">/</span> {project.title}</div>
  <section className="rounded-3xl bg-slate-950 p-8 text-white"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-xs font-black uppercase tracking-[0.2em] text-emerald-300">{STATUS_LABELS[project.status]||project.status}</div><h1 className="mt-2 text-4xl font-black tracking-tight">{project.title}</h1><p className="mt-4 max-w-3xl leading-8 text-slate-300">{project.research_question||'Your research question is still being refined.'}</p></div><div className="min-w-[150px] rounded-2xl bg-white/10 p-5 text-center"><div className="text-4xl font-black text-emerald-300">{project.readiness_score}%</div><div className="mt-1 text-xs font-bold text-slate-300">project readiness</div></div></div>
   <div className="mt-8 flex flex-wrap gap-2">{STATUS_ORDER.map((s,i)=><button key={s} onClick={()=>advance(s)} className={`rounded-full px-3 py-2 text-xs font-black ${i<=currentIndex?'bg-emerald-300 text-slate-950':'bg-white/10 text-slate-300'}`}>{i+1}. {STATUS_LABELS[s]}</button>)}</div>
  </section>
  {message&&<div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{message}</div>}
  <section className="mt-6 grid gap-6 lg:grid-cols-[1.55fr_0.85fr]">
   <div className="space-y-6">
    <section className="rounded-3xl border border-slate-200 bg-white p-7"><div className="flex items-end justify-between"><div><div className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">Research core</div><h2 className="mt-2 text-2xl font-black">What are you actually studying?</h2></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black">{project.discipline||'Health research'}</span></div><div className="mt-6 grid gap-5 md:grid-cols-2">{[['Background',project.background],['Objectives',project.objectives],['Methodology',project.methodology],['Study type',project.study_type]].map(([l,v])=><div key={l} className="rounded-2xl bg-slate-50 p-5"><div className="text-xs font-black uppercase tracking-wide text-slate-400">{l}</div><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-slate-700">{v||'Not defined yet.'}</p></div>)}</div></section>
    <section className="rounded-3xl border border-slate-200 bg-white p-7"><div className="flex items-end justify-between"><div><div className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">Execution</div><h2 className="mt-2 text-2xl font-black">Milestones</h2><p className="mt-2 text-sm text-slate-500">Break the project into visible pieces so momentum does not disappear between meetings.</p></div><div className="text-sm font-black text-slate-500">{done}/{project.milestones?.length||0} done</div></div><div className="mt-6 space-y-3">{(project.milestones||[]).map((m:any)=><div key={m.id} className="flex gap-4 rounded-2xl border border-slate-100 p-4"><div className={`mt-1 h-3 w-3 rounded-full ${m.status==='done'?'bg-emerald-500':m.status==='blocked'?'bg-rose-500':'bg-slate-300'}`}/><div className="min-w-0 flex-1"><div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"><h3 className="font-black">{m.title}</h3><span className="text-xs font-bold uppercase tracking-wide text-slate-400">{m.status.replaceAll('_',' ')}</span></div><p className="mt-1 text-sm leading-6 text-slate-600">{m.description||'No description yet.'}</p>{m.due_date&&<div className="mt-2 text-xs font-bold text-slate-400">Due {m.due_date}</div>}</div></div>)}{(!project.milestones||project.milestones.length===0)&&<div className="rounded-2xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-500">No milestones yet. Add the first one below.</div>}</div><form onSubmit={addMilestone} className="mt-6 grid gap-3 md:grid-cols-[1.2fr_1fr_0.7fr_auto]"><input required value={milestone.title} onChange={e=>setMilestone({...milestone,title:e.target.value})} placeholder="Milestone title" className="rounded-xl border px-4 py-3 text-sm"/><input value={milestone.description} onChange={e=>setMilestone({...milestone,description:e.target.value})} placeholder="What does done look like?" className="rounded-xl border px-4 py-3 text-sm"/><input type="date" value={milestone.due_date} onChange={e=>setMilestone({...milestone,due_date:e.target.value})} className="rounded-xl border px-4 py-3 text-sm"/><button disabled={saving} className="rounded-xl bg-slate-950 px-4 py-3 text-xs font-black text-white">{saving?'Adding…':'Add'}</button></form></section>
   </div>
   <aside className="space-y-6">
    <section className="rounded-3xl border border-slate-200 bg-white p-7"><div className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">Readiness</div><div className="mt-3 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{width:`${project.readiness_score}%`}}/></div><div className="mt-2 text-3xl font-black">{project.readiness_score}%</div><div className="mt-4 space-y-2 text-sm">{[['Question',project.research_question],['Objectives',project.objectives],['Methodology',project.methodology],['Mentor',project.mentor],['Ethics',project.ethics_status==='approved'||project.ethics_status==='not_required']].map(([l,v])=><div key={l} className="flex items-center justify-between gap-3 rounded-xl bg-slate-50 p-3"><span className="font-bold text-slate-600">{l}</span><span className="font-black">{v===true?'Ready':v?'Added':'Needs work'}</span></div>)}</div></section>
    <section className="rounded-3xl border border-slate-200 bg-white p-7"><div className="text-xs font-black uppercase tracking-[0.18em] text-blue-700">People</div><h2 className="mt-2 text-xl font-black">Team & mentor</h2><div className="mt-4 rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black uppercase tracking-wide text-slate-400">Mentor</div><div className="mt-1 font-black">{project.mentor_profile?.full_name||project.mentor_profile?.username||'No mentor assigned'}</div></div><div className="mt-3 space-y-2">{(project.members||[]).slice(0,5).map((m:any)=><div key={m.id} className="flex items-center justify-between rounded-xl border border-slate-100 p-3"><span className="font-bold">{m.user_profile?.full_name||m.user_profile?.username||`Member ${m.user}`}</span><span className="text-xs font-bold text-slate-400">{m.role?.replaceAll('_',' ')}</span></div>)}</div><Link href="/collaboration" className="mt-4 inline-flex w-full justify-center rounded-xl bg-blue-50 px-4 py-3 text-xs font-black text-blue-800">Find people for this work →</Link></section>
    <section className="rounded-3xl border border-amber-200 bg-amber-50 p-7"><div className="text-xs font-black uppercase tracking-[0.18em] text-amber-700">Governance</div><h2 className="mt-2 text-xl font-black text-amber-950">Keep the study safe.</h2><p className="mt-2 text-sm leading-6 text-amber-900">RSRE guidance can help prepare your project, but it does not grant statutory ethics approval.</p><div className="mt-4 grid gap-2 text-sm"><div className="rounded-xl bg-white/70 p-3 font-bold">Ethics: {project.ethics_status.replaceAll('_',' ')}</div><div className="rounded-xl bg-white/70 p-3 font-bold">Data governance: {project.data_governance_status.replaceAll('_',' ')}</div></div><Link href="/ethics-compliance" className="mt-4 inline-flex w-full justify-center rounded-xl bg-amber-950 px-4 py-3 text-xs font-black text-white">Open governance workspace →</Link></section>
    {nextStatus&&project.status!=='completed'&&<button onClick={()=>advance(nextStatus)} className="w-full rounded-2xl bg-emerald-600 px-5 py-4 text-sm font-black text-white shadow-sm">Next stage: {STATUS_LABELS[nextStatus]} →</button>}
    {project.status==='manuscript'&&<Link href="/submit" className="flex w-full justify-center rounded-2xl border border-slate-200 bg-white px-5 py-4 text-sm font-black text-slate-950">Move toward RSJH submission →</Link>}
   </aside>
  </section>
  <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-7"><div className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">Architecture boundary</div><div className="mt-4 grid gap-3 md:grid-cols-4 text-sm"><div className="rounded-2xl bg-emerald-50 p-4"><b>Academy</b><div className="mt-1 text-slate-600">Learn and practice.</div></div><div className="rounded-2xl bg-blue-50 p-4"><b>Sandbox</b><div className="mt-1 text-slate-600">Experiment with data.</div></div><div className="rounded-2xl bg-violet-50 p-4"><b>Incubator</b><div className="mt-1 text-slate-600">Run the real project.</div></div><div className="rounded-2xl bg-slate-100 p-4"><b>RSJH</b><div className="mt-1 text-slate-600">Publish through the protected workflow.</div></div></div></section>
 </main></ApplicationShell>
}
